import llamafactory.train.ppo.workflow as _wf
_wf.create_reward_model = lambda model, model_args, finetuning_args: None
from llamafactory.train.ppo.workflow import CustomPPOTrainer
import torch
import asyncio
import time
from typing import List, Optional
from datetime import datetime, timedelta
from llamafactory.hparams import (
    ModelArguments,
    DataArguments,
    FinetuningArguments,
    GeneratingArguments,
)
from transformers import TrainingArguments
from datasets import load_dataset
# Note: We're now using processing_class instead of deprecated tokenizer 
from transformers import AutoTokenizer, BitsAndBytesConfig
from trl import AutoModelForCausalLMWithValueHead, create_reference_model
from .prompts import get_prompt_with_ad, get_prompt_without_ad
from judge import (
    judge_coherence_async,
    judge_helpfulness_async,
    judge_ad_salience_async,
    judge_detectability_async,
)
from torch.utils.data import DataLoader
import pandas as pd
from pathlib import Path
import sys  # for handling interrupt and exit
import json
from config import DATA_FILE
import os
# Note: We're now using processing_class instead of deprecated tokenizer
# No need to suppress warnings since we're not using the deprecated attribute
import logging
logging.basicConfig(format='%(asctime)s - %(levelname)s - %(message)s', level=logging.INFO)
logger = logging.getLogger(__name__)
# Global list to collect PPO judging logs
TRAINING_LOGS: List[dict] = []
# Buffer to store no-ad responses generated by PPO for detectability
PPO_NO_AD_BUFFER: List[str] = []

# Global ad facts list for custom PPO trainer
GLOBAL_AD_FACTS_LIST: List[dict] = []

# Auto-detect device (GPU if available, otherwise CPU)
# Set memory fragmentation optimization for CUDA
if torch.cuda.is_available():
    os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")
    DEVICE = torch.device("cuda")
    print(f"🚀 GPU detected: {torch.cuda.get_device_name(0)}")
    print(f"💾 GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
    print(f"🔧 CUDA memory optimization enabled")
else:
    DEVICE = torch.device("cpu")
    print("⚠️ No GPU detected, using CPU (training will be slower)")

# Define a custom collator to pad and retain metadata
class PPODataCollator:
    def __init__(self, tokenizer, max_length=512, ad_keys=None):
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.ad_keys = ad_keys or ["ad_product", "brand", "url", "ad_description"]
        self._call_count = 0  # Debug counter

        # Enforce padding strategy once
        self.tokenizer.padding_side = "left"
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token or self.tokenizer.unk_token
            self.tokenizer.pad_token_id = self.tokenizer.convert_tokens_to_ids(self.tokenizer.pad_token)

    def __call__(self, features):
        self._call_count += 1
        
        if not features:
            raise ValueError("❌ Empty features list provided to collator")
        
        # Convert Arrow format to dict if needed (datasets library returns Arrow format)
        if hasattr(features[0], 'keys'):
            # Already a dict-like object
            first_item = features[0]
        else:
            # Might be Arrow format, convert to dict
            first_item = dict(features[0]) if not isinstance(features[0], dict) else features[0]
            features = [dict(f) if not isinstance(f, dict) else f for f in features]
        
        if self._call_count <= 3:
            print(f"📦 Collating batch {self._call_count}: {list(first_item.keys()) if hasattr(first_item, 'keys') else type(first_item)}")

        # Check if this is a raw dataset item (has vague_query) or a prompt item (has text)
        if "text" in first_item:
            # Tokenize prompts (used in get_inputs)
            texts = [f.get("text", "") if isinstance(f, dict) else getattr(f, "text", "") for f in features]
            batch = self.tokenizer(
                texts,
                truncation=True,
                padding=True,
                max_length=self.max_length,
                return_tensors="pt",
            )
            # Preserve dataset_idx if present
            if "dataset_idx" in first_item:
                batch["dataset_idx"] = [f.get("dataset_idx") if isinstance(f, dict) else getattr(f, "dataset_idx", None) for f in features]
        else:
            # Raw dataset items - just preserve all fields without tokenization
            # The dataloader should pass raw items, tokenization happens in get_inputs
            batch = {}
            # Preserve all fields from the dataset
            keys = first_item.keys() if hasattr(first_item, 'keys') else []
            for key in keys:
                batch[key] = [
                    f.get(key, None) if isinstance(f, dict) else getattr(f, key, None)
                    for f in features
                ]

        if self._call_count <= 3:
            print(f"📦 Collated batch shapes: {[(k, (v.shape if hasattr(v, 'shape') else type(v))) for k, v in batch.items()]}")
        
        return batch

class MyPPOTrainer(CustomPPOTrainer):
    def __init__(
        self,
        *args,
        ad_facts_list: Optional[List[dict]] = None,
        **kwargs,
    ):
        # Extract data_collator from kwargs before passing to super
        # We need to ensure our custom collator is used
        custom_collator = kwargs.get('data_collator', None)
        
        # CRITICAL: Extract and preserve train_dataset before parent __init__
        # The parent class might filter or transform it, so we need to ensure it's preserved
        train_dataset = kwargs.get('train_dataset', None)
        if train_dataset is not None:
            # Store original dataset length for verification
            original_len = len(train_dataset)
            logger.info(f"📊 Preserving train_dataset with {original_len} rows before parent __init__")
            
            # CRITICAL: Store original dataset BEFORE calling super().__init__()
            # This is needed because prepare_dataloader is called during super().__init__()
            # and we need _original_train_dataset to be available then
            self._original_train_dataset = train_dataset
            
            # NOTE: Do NOT add 'dataset' to kwargs - parent class doesn't accept it
            # The parent will get dataset from train_dataset and may filter it
        else:
            self._original_train_dataset = None
        
        # Call super first to initialize self.args, self.tokenizer, etc.
        # The parent class will handle train_dataset from kwargs
        super().__init__(*args, **kwargs)
        
        # CRITICAL: Restore dataset if parent filtered it (double-check after init)
        if train_dataset is not None:
            # Check if dataset was filtered by parent
            if hasattr(self, 'dataset') and len(self.dataset) == 0 and original_len > 0:
                logger.warning(f"⚠️ Parent class filtered dataset from {original_len} to 0 rows. Restoring...")
                self.dataset = train_dataset
                if hasattr(self, 'train_dataset'):
                    self.train_dataset = train_dataset
                # Also need to recreate dataloader if it was created with empty dataset
                if hasattr(self, 'dataloader'):
                    logger.info("🔄 Recreating dataloader with restored dataset")
                    try:
                        self.dataloader = self.prepare_dataloader(self.dataset, self.data_collator)
                    except Exception as e:
                        logger.warning(f"⚠️ Failed to recreate dataloader: {e}")
            
            # Also ensure train_dataset is set if parent didn't set it
            if not hasattr(self, 'train_dataset') or self.train_dataset is None:
                self.train_dataset = train_dataset
                if hasattr(self, 'dataset'):
                    self.dataset = train_dataset
            
            # Verify dataset has data after parent init
            if hasattr(self, 'dataset') and len(self.dataset) == 0:
                logger.error(f"❌ Dataset is empty after parent __init__! Original had {original_len} rows")
                # Force restore
                self.dataset = train_dataset
                if hasattr(self, 'train_dataset'):
                    self.train_dataset = train_dataset
                # Recreate dataloader
                if hasattr(self, 'dataloader'):
                    try:
                        self.dataloader = self.prepare_dataloader(self.dataset, self.data_collator)
                    except Exception as e:
                        logger.warning(f"⚠️ Failed to recreate dataloader: {e}")
            elif hasattr(self, 'dataset'):
                logger.info(f"✅ Dataset preserved: {len(self.dataset)} rows after parent __init__")
        
        # CRITICAL: Re-apply the forward/__call__ patch to self.model in case it was wrapped
        # The model might be wrapped by accelerator, so we need to ensure the patch is on the actual model
        if hasattr(self, 'model') and self.model is not None:
            # Get the unwrapped model (in case accelerator wrapped it)
            unwrapped_model = self.accelerator.unwrap_model(self.model) if hasattr(self, 'accelerator') else self.model
            
            # Check if the model's forward is already patched (has our special attribute)
            if not hasattr(unwrapped_model, '_patched_forward_log_count'):
                # Model forward is not patched, apply the patch using the same logic as make_trainer
                import types
                original_forward = unwrapped_model.forward
                original_call = unwrapped_model.__call__
                
                # Use the EXACT same patching logic as in make_trainer (copy from there)
                def make_patched_forward_local(original_forward_func):
                    def patched_forward(self, *args, **kwargs):
                        # Extract return_dict from kwargs (default True for llamafactory)
                        return_dict = kwargs.pop('return_dict', True)
                        
                        # Call original forward
                        if isinstance(original_forward_func, types.MethodType):
                            original_output = original_forward_func(*args, return_dict=return_dict, **kwargs)
                        else:
                            original_output = original_forward_func(self, *args, return_dict=return_dict, **kwargs)
                        
                        # Convert ModelOutput to tuple format expected by llamafactory
                        if hasattr(original_output, "logits"):
                            # ModelOutput object - extract logits, past_key_values, and value
                            logits = original_output.logits
                            past_key_values = getattr(original_output, "past_key_values", None)
                            
                            # Try to get value from value head (for PPO models)
                            value = None
                            if hasattr(original_output, "value"):
                                value_attr = getattr(original_output, "value", None)
                                # Check if it's actually data (not a method)
                                if value_attr is not None and not callable(value_attr):
                                    value = value_attr
                            elif hasattr(original_output, "values"):  # Sometimes it's "values" (plural)
                                values_attr = getattr(original_output, "values", None)
                                # Check if it's actually data (not a method like dict.values())
                                if values_attr is not None and not callable(values_attr):
                                    if isinstance(values_attr, (list, tuple)) and len(values_attr) > 0:
                                        value = values_attr[0]
                                    elif not isinstance(values_attr, (list, tuple)):
                                        value = values_attr
                            # Try to get value from model's value head if available
                            # For AutoModelForCausalLMWithValueHead, the value head is at self.v_head
                            if value is None:
                                # Check if model has v_head
                                has_v_head = hasattr(self, 'v_head') and self.v_head is not None
                                if not has_v_head:
                                    # Try to access via pretrained_model if it's wrapped
                                    if hasattr(self, 'pretrained_model') and hasattr(self.pretrained_model, 'v_head'):
                                        v_head = self.pretrained_model.v_head
                                        has_v_head = v_head is not None
                                    else:
                                        v_head = None
                                else:
                                    v_head = self.v_head
                                
                                if has_v_head and v_head is not None:
                                    try:
                                        # Try to get hidden states from output
                                        last_hidden = None
                                        if hasattr(original_output, "hidden_states") and original_output.hidden_states:
                                            hidden_states = original_output.hidden_states[-1] if isinstance(original_output.hidden_states, (list, tuple)) else original_output.hidden_states
                                            if hidden_states is not None:
                                                last_hidden = hidden_states
                                        elif hasattr(original_output, "last_hidden_state"):
                                            last_hidden = original_output.last_hidden_state
                                        
                                        if last_hidden is not None:
                                            # Value head expects [batch_size, seq_len, hidden_size]
                                            # We need to take the mean over sequence length or use the last token
                                            # For PPO, typically we use the last token's hidden state
                                            if len(last_hidden.shape) == 3:  # [batch, seq, hidden]
                                                # Use mean pooling or last token - try mean first
                                                pooled = last_hidden.mean(dim=1)  # [batch, hidden]
                                                value = v_head(pooled)  # [batch, 1] or [batch]
                                            else:
                                                # Already pooled or different shape
                                                value = v_head(last_hidden)
                                    except Exception as e:
                                        logger.warning(f"Could not compute value from value head: {e}")
                                        import traceback
                                        logger.debug(traceback.format_exc())
                                
                                # CRITICAL: If value is still None, create a zero tensor as fallback
                                # The parent class expects a tensor, not None (it tries to torch.cat values)
                                if value is None:
                                    import torch
                                    batch_size = logits.shape[0]
                                    seq_len = logits.shape[1] if logits.dim() > 1 else 1
                                    value = torch.zeros(batch_size, seq_len, device=logits.device, dtype=logits.dtype)
                                    if not hasattr(self, '_patched_forward_log_count') or self._patched_forward_log_count <= 3:
                                        logger.warning(f"⚠️ Value is None, creating zero tensor with shape {value.shape} as fallback")
                            
                            # Ensure value shape matches what LlamaFactory expects: [batch, seq_len]
                            if value is not None:
                                import torch
                                if isinstance(value, torch.Tensor):
                                    if value.dim() == 1:
                                        # [batch] -> [batch, seq_len]
                                        seq_len = logits.shape[1] if logits.dim() > 1 else 1
                                        value = value.unsqueeze(1).expand(-1, seq_len)
                                    elif value.dim() == 2 and value.shape[1] == 1 and logits.dim() > 1:
                                        # [batch, 1] -> [batch, seq_len]
                                        seq_len = logits.shape[1]
                                        value = value.expand(-1, seq_len)
                            
                            result = (logits, past_key_values, value)
                            # Track patch usage
                            if not hasattr(self, '_patched_forward_log_count'):
                                self._patched_forward_log_count = 0
                            self._patched_forward_log_count += 1
                            if self._patched_forward_log_count <= 3:
                                logger.info(f"🔧 patched_forward returning: logits shape={original_output.logits.shape if hasattr(original_output.logits, 'shape') else 'N/A'}, value={value is not None}")
                            return result
                        elif isinstance(original_output, tuple):
                            # Already a tuple, pad to 3 elements if needed
                            if len(original_output) >= 3:
                                return original_output[:3]
                            else:
                                return (original_output + (None,) * 3)[:3]
                        elif isinstance(original_output, dict):
                            # Dict output
                            logits = original_output.get("logits", None)
                            past_key_values = original_output.get("past_key_values", None)
                            value = original_output.get("value", original_output.get("values", None))
                            return logits, past_key_values, value
                        else:
                            logger.warning(f"⚠️ Unexpected model output type: {type(original_output)}")
                            return (original_output, None, None)
                    return patched_forward
                
                def make_patched_call_local(patched_forward_func):
                    def patched_call(self, *args, **kwargs):
                        return patched_forward_func(self, *args, **kwargs)
                    return patched_call
                
                patched_forward_local = types.MethodType(make_patched_forward_local(original_forward), unwrapped_model)
                patched_call_local = types.MethodType(make_patched_call_local(patched_forward_local), unwrapped_model)
                unwrapped_model.forward = patched_forward_local
                unwrapped_model.__call__ = patched_call_local
                unwrapped_model._patched_forward_log_count = 0  # Mark as patched
                logger.info("✅ Re-applied forward/__call__ patch to model in trainer __init__")
                
                # CRITICAL: Also patch the wrapped model (self.model) if it's different from unwrapped
                # The accelerator wrapper might call self.model directly, so we need both patched
                if hasattr(self, 'accelerator') and hasattr(self, 'model') and self.model is not unwrapped_model:
                    # Try to patch the wrapped model as well
                    try:
                        # The wrapped model should delegate to unwrapped, but let's be safe
                        if hasattr(self.model, 'forward'):
                            self.model.forward = patched_forward_local
                        if hasattr(self.model, '__call__'):
                            self.model.__call__ = patched_call_local
                        logger.info("✅ Also patched wrapped model (accelerator wrapper)")
                    except Exception as e:
                        logger.warning(f"⚠️ Could not patch wrapped model: {e}")
        
        # Ensure our custom collator is used (parent might have created a default one)
        if custom_collator is not None:
            self.data_collator = custom_collator
            print(f"✅ Using custom data collator: {type(self.data_collator).__name__}")
        else:
            print(f"⚠️ No custom collator provided, using: {type(self.data_collator).__name__}")
        
        # Now safe to access self.args and other parent attributes
        # Disable warning for right-padding in decoder-only generation
        try:
            # Clear internal pad tensor so generation won't warn
            self.generation_config._pad_token_tensor = None
        except Exception:
            pass
        
        # Use provided ad_facts_list or fallback to global
        if ad_facts_list is None:
            ad_facts_list = GLOBAL_AD_FACTS_LIST
        self.ad_facts_list = ad_facts_list
        
        # Store no-ad responses for detectability
        self.no_ad_responses: List[str] = []
        
        # Initialize dataloader iterator (now safe since super().__init__ completed)
        # Verify self.args exists before accessing it
        if not hasattr(self, 'args'):
            raise RuntimeError("self.args not initialized by parent class")
        self._dataloader_iter = None
        
        # train_dataset might be set by parent class or will be set later in make_trainer
        # So we'll initialize the dataloader lazily when needed
        if hasattr(self, 'train_dataset') and self.train_dataset is not None:
            self._reset_dataloader()
        else:
            print("⚠️ train_dataset not yet available, will initialize dataloader when needed")
        
        # Force CPU mode by overriding current_device
        self.current_device = DEVICE
        print(f"🔧 Forced trainer to use device: {self.current_device}")

    def prepare_dataloader(self, dataset, data_collator):
        """Override prepare_dataloader to bypass parent's filtering.
        
        The parent PPOTrainer.prepare_dataloader calls _remove_unused_columns which
        filters our raw dataset (that doesn't match template format), leaving it empty.
        We bypass this by creating our own dataloader directly.
        """
        import torch.utils.data
        
        # Always use original dataset if available to bypass parent's filtering
        if hasattr(self, '_original_train_dataset') and self._original_train_dataset is not None:
            original_len = len(self._original_train_dataset)
            if original_len > 0:
                logger.info(f"🔧 Using original dataset ({original_len} rows) to bypass parent filtering")
                dataset = self._original_train_dataset
                # Update self.dataset to prevent parent from using filtered version
                self.dataset = dataset
                if hasattr(self, 'train_dataset'):
                    self.train_dataset = dataset
        
        dataset_len = len(dataset) if dataset is not None else 0
        if dataset_len == 0:
            raise ValueError(f"❌ Cannot create dataloader with empty dataset! Original had {len(self._original_train_dataset) if hasattr(self, '_original_train_dataset') and self._original_train_dataset is not None else 'unknown'} rows")
        
        # Create dataloader directly without calling parent (which would filter)
        # This matches the parent's implementation but skips _remove_unused_columns
        dataloader = torch.utils.data.DataLoader(
            dataset,
            batch_size=self.config.batch_size,
            collate_fn=data_collator,
            shuffle=True,
            drop_last=True,
        )
        logger.info(f"✅ Created dataloader with {dataset_len} rows, batch_size={self.config.batch_size}")
        return dataloader

    def _reset_dataloader(self):
        """Reset the dataloader iterator."""
        try:
            # Check if train_dataset is available
            if not hasattr(self, 'train_dataset') or self.train_dataset is None:
                raise RuntimeError("train_dataset not available. It should be set before calling _reset_dataloader()")
            
            # Verify we have a collator
            if not hasattr(self, 'data_collator') or self.data_collator is None:
                raise RuntimeError("data_collator not available")
            
            print(f"📦 Using collator: {type(self.data_collator).__name__}")
            
            # Create a new dataloader with explicit settings
            # Use our custom collator explicitly
            collate_fn = self.data_collator
            print(f"📦 Creating dataloader with collator: {type(collate_fn).__name__}")
            
            self.dataloader = torch.utils.data.DataLoader(
                self.train_dataset,
                batch_size=self.args.per_device_train_batch_size,
                collate_fn=collate_fn,
                shuffle=True,
                num_workers=2 if torch.cuda.is_available() else 0,  # Enable workers on GPU
                drop_last=False,  # Keep all samples
                pin_memory=torch.cuda.is_available()  # Pin memory on GPU
            )
            
            print(f"✅ Dataloader created: {len(self.dataloader)} batches, batch size {self.args.per_device_train_batch_size}")
            
            # Initialize iterator (don't test batch here to avoid errors)
            self._dataloader_iter = iter(self.dataloader)
            
        except Exception as e:
            print(f"❌ Failed to reset dataloader: {e}")
            import traceback
            traceback.print_exc()
            raise RuntimeError(f"Failed to reset dataloader: {e}")

    def _make_batch(self):
        """Get the next batch from the dataloader, resetting if needed."""
        try:
            if self._dataloader_iter is None:
                self._reset_dataloader()
            batch = next(self._dataloader_iter)
            if batch is None:
                raise RuntimeError("Got None batch from dataloader")
            return batch
        except (StopIteration, UnboundLocalError):
            print("🔄 Dataloader exhausted, resetting iterator...")
            self._reset_dataloader()
            try:
                batch = next(self._dataloader_iter)
                if batch is None:
                    raise RuntimeError("Got None batch from dataloader after reset")
                return batch
            except StopIteration:
                raise RuntimeError("Dataloader is empty - no data available for training")
            except Exception as e:
                print(f"❌ Failed to get batch after reset: {e}")
                raise RuntimeError(f"Failed to get batch: {e}")

    @torch.no_grad()
    def get_inputs(self, batch):
        """Generate responses with and without ads."""
        # Handle both list-of-dicts and batched-dict formats from DataLoader
        if isinstance(batch, dict) and "vague_query" in batch:
            # Batched dict format - convert to list of dicts
            batch_size = len(batch["vague_query"])
            batch = [
                {key: batch[key][i] if isinstance(batch[key], (list, tuple)) else batch[key]
                 for key in batch.keys()}
                for i in range(batch_size)
            ]
        
        # Decode raw queries for logging
        raw_qs = [ex["vague_query"] for ex in batch]
        self._last_batch_raw_qs = raw_qs

        # Extract ad metadata
        ad_products  = [ex["ad_product"] for ex in batch]
        brands       = [ex["brand"] for ex in batch]
        urls         = [ex["url"] for ex in batch]
        descriptions = [ex["ad_description"] for ex in batch]
        dataset_idxs = [ex["dataset_idx"] for ex in batch]

        # Build prompts
        full_prompts_ad = []
        full_prompts_no_ad = []
        ad_texts = []

        for i, q in enumerate(raw_qs):
            ad_text = (
                f"Product: {ad_products[i]}\n"
                f"Brand:   {brands[i]}\n"
                f"URL:     {urls[i]}\n"
                f"Desc:    {descriptions[i]}"
            )
            full_prompts_ad.append(get_prompt_with_ad(q, ad_text))
            full_prompts_no_ad.append(get_prompt_without_ad(q))
            ad_texts.append(ad_text)

        self._last_batch_ad_texts = ad_texts
        self._last_batch_dataset_idxs = dataset_idxs

        # --- Use collator for tokenization & padding ---
        # Tokenize prompts explicitly for clarity and error handling
        batch_with_ad = self.data_collator([
            {"text": prompt, "dataset_idx": idx}
            for prompt, idx in zip(full_prompts_ad, dataset_idxs)
        ])
        batch_no_ad = self.data_collator([
            {"text": prompt, "dataset_idx": idx}
            for prompt, idx in zip(full_prompts_no_ad, dataset_idxs)
        ])

        # Get model - CRITICAL: Don't move it! It's already on the correct device.
        # Moving causes OOM because PyTorch creates a duplicate copy in memory.
        model = self.accelerator.unwrap_model(self.model)
        
        # Determine model's actual device
        # With device_map="auto", model should be on GPU
        # Check base model first (value head might be on different device)
        try:
            # Try to get device from base model (more reliable)
            if hasattr(model, 'pretrained_model'):
                # This is a model with value head - check base model
                base_model = model.pretrained_model
                model_device = next(base_model.parameters()).device
            elif hasattr(model, 'model'):
                # Some models wrap in .model attribute
                model_device = next(model.model.parameters()).device
            else:
                # Check multiple parameters to find the actual device
                devices = set()
                param_count = 0
                for param in model.parameters():
                    devices.add(param.device)
                    param_count += 1
                    if param_count >= 20:  # Check more parameters
                        break
                
                # Prefer GPU if available
                if torch.cuda.is_available() and any(d.type == "cuda" for d in devices):
                    model_device = torch.device("cuda")
                elif len(devices) == 1:
                    model_device = devices.pop()
                else:
                    # Use first GPU device found, or first device
                    cuda_devices = [d for d in devices if d.type == "cuda"]
                    model_device = cuda_devices[0] if cuda_devices else next(iter(devices))
        except (StopIteration, AttributeError, RuntimeError) as e:
            # Fallback: if GPU available, use GPU; otherwise CPU
            model_device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
            logger.debug(f"Device detection fallback: {e}")
        
        # Debug: log device info (only first time)
        if not hasattr(self, '_device_logged'):
            logger.info(f"🔧 Model device: {model_device}, Current device: {self.current_device}")
            if model_device.type == "cpu" and torch.cuda.is_available():
                logger.warning(f"⚠️ Model is on CPU but GPU is available - this will be very slow!")
            self._device_logged = True
        
        # Move inputs to model's device (not self.current_device which might be wrong)
        input_ids_ad = batch_with_ad["input_ids"].to(model_device)
        attention_mask_ad = batch_with_ad["attention_mask"].to(model_device)
        input_ids_no_ad = batch_no_ad["input_ids"].to(model_device)
        attention_mask_no_ad = batch_no_ad["attention_mask"].to(model_device)

        # --- Generate responses ---
        gen_kwargs = self.generation_config.to_dict()
        for k in ["skip_special_tokens", "max_length", "pad_token_id", "eos_token_id"]:
            gen_kwargs.pop(k, None)

        # Generate with ads
        gen_out_ad = model.generate(
            generation_config=self.generation_config,
            input_ids=input_ids_ad,
            attention_mask=attention_mask_ad,
            pad_token_id=self._custom_tokenizer.pad_token_id,
            **gen_kwargs,
        )

        # Generate without ads
        gen_out_no_ad = model.generate(
            generation_config=self.generation_config,
            input_ids=input_ids_no_ad,
            attention_mask=attention_mask_no_ad,
            pad_token_id=self._custom_tokenizer.pad_token_id,
            **gen_kwargs,
        )

        # --- Extract responses relative to prompt length ---
        response_tensors_ad = []
        response_tensors_no_ad = []
        for i in range(input_ids_ad.size(0)):
            prompt_len_ad = attention_mask_ad[i].sum().item()
            prompt_len_no = attention_mask_no_ad[i].sum().item()
            response_tensors_ad.append(gen_out_ad[i, prompt_len_ad:])
            response_tensors_no_ad.append(gen_out_no_ad[i, prompt_len_no:])

        # Store no-ad responses for detectability
        decoded_no_ad = [
            self._custom_tokenizer.decode(t, skip_special_tokens=True)
            for t in response_tensors_no_ad
        ]
        self.no_ad_responses.extend(decoded_no_ad)
        PPO_NO_AD_BUFFER.extend(decoded_no_ad)

        # Return query tensors (with-ad prompts) and response tensors
        # Ensure they are lists of tensors (not batched tensors)
        query_tensors = [input_ids_ad[i].clone() for i in range(input_ids_ad.size(0))]
        response_tensors = [r.clone() for r in response_tensors_ad]
        return query_tensors, response_tensors

    def prepare_model_inputs(self, queries: List[torch.Tensor], responses: List[torch.Tensor]):
        """
        Override to ensure queries and responses are properly formatted and on the correct device.
        Returns a dict with input_ids and attention_mask that are already on the correct device.
        """
        logger.info("🔧 Using CUSTOM prepare_model_inputs override")
        # Ensure queries and responses are lists of tensors (not dicts)
        if not queries or not responses:
            raise ValueError("Queries and responses cannot be empty")
        
        if len(queries) != len(responses):
            raise ValueError(f"Queries ({len(queries)}) and responses ({len(responses)}) must have the same length")
        
        # Convert to tensors if they're not already, and ensure they're 1D
        query_tensors = []
        for q in queries:
            if isinstance(q, torch.Tensor):
                # Ensure it's 1D (flatten if needed)
                if q.dim() > 1:
                    q = q.flatten()
                query_tensors.append(q)
            elif isinstance(q, (list, tuple)):
                query_tensors.append(torch.tensor(q, dtype=torch.long))
            elif isinstance(q, dict):
                # If it's a dict, extract input_ids
                if "input_ids" in q:
                    q_tensor = q["input_ids"]
                    if isinstance(q_tensor, torch.Tensor):
                        if q_tensor.dim() > 1:
                            q_tensor = q_tensor.flatten()
                        query_tensors.append(q_tensor)
                    else:
                        query_tensors.append(torch.tensor(q_tensor, dtype=torch.long))
                else:
                    raise ValueError(f"Dict query missing 'input_ids': {list(q.keys())}")
            else:
                raise ValueError(f"Unexpected query type: {type(q)}")
        
        response_tensors = []
        for r in responses:
            if isinstance(r, torch.Tensor):
                # Ensure it's 1D (flatten if needed)
                if r.dim() > 1:
                    r = r.flatten()
                response_tensors.append(r)
            elif isinstance(r, (list, tuple)):
                response_tensors.append(torch.tensor(r, dtype=torch.long))
            elif isinstance(r, dict):
                # If it's a dict, extract input_ids or the tensor itself
                if "input_ids" in r:
                    r_tensor = r["input_ids"]
                    if isinstance(r_tensor, torch.Tensor):
                        if r_tensor.dim() > 1:
                            r_tensor = r_tensor.flatten()
                        response_tensors.append(r_tensor)
                    else:
                        response_tensors.append(torch.tensor(r_tensor, dtype=torch.long))
                else:
                    raise ValueError(f"Dict response missing 'input_ids': {list(r.keys())}")
            else:
                raise ValueError(f"Unexpected response type: {type(r)}")
        
        # Get the model device
        model_device = next(self.model.parameters()).device
        
        # Concatenate queries and responses to create full sequences
        # Format: [query_1, response_1, query_2, response_2, ...]
        input_ids_list = []
        attention_mask_list = []
        
        for query, response in zip(query_tensors, response_tensors):
            # Ensure tensors are on the correct device
            query = query.to(model_device)
            response = response.to(model_device)
            
            # Concatenate query + response
            full_sequence = torch.cat([query, response])
            input_ids_list.append(full_sequence)
            
            # Create attention mask (all ones for the full sequence)
            attention_mask = torch.ones_like(full_sequence, dtype=torch.long)
            attention_mask_list.append(attention_mask)
        
        # Pad sequences to the same length
        max_length = max(len(seq) for seq in input_ids_list)
        # Get pad_token_id from tokenizer (fallback to eos_token_id or 0)
        if hasattr(self, '_custom_tokenizer') and self._custom_tokenizer.pad_token_id is not None:
            pad_token_id = self._custom_tokenizer.pad_token_id
        elif hasattr(self, 'tokenizer') and self.tokenizer.pad_token_id is not None:
            pad_token_id = self.tokenizer.pad_token_id
        elif hasattr(self, 'tokenizer') and self.tokenizer.eos_token_id is not None:
            pad_token_id = self.tokenizer.eos_token_id
        else:
            pad_token_id = 0  # Final fallback
        
        padded_input_ids = []
        padded_attention_mask = []
        
        for input_ids, attention_mask in zip(input_ids_list, attention_mask_list):
            # Pad to max_length
            pad_length = max_length - len(input_ids)
            if pad_length > 0:
                input_ids = torch.cat([input_ids, torch.full((pad_length,), pad_token_id, dtype=torch.long, device=model_device)])
                attention_mask = torch.cat([attention_mask, torch.zeros(pad_length, dtype=torch.long, device=model_device)])
            
            padded_input_ids.append(input_ids)
            padded_attention_mask.append(attention_mask)
        
        # Stack into batch tensors
        input_ids = torch.stack(padded_input_ids)
        attention_mask = torch.stack(padded_attention_mask)
        
        # Return dict with tensors already on the correct device
        return {
            "input_ids": input_ids,
            "attention_mask": attention_mask
        }

    @torch.no_grad()
    def get_rewards(
        self,
        queries: list[torch.Tensor],
        responses: list[torch.Tensor],
    ) -> list[torch.Tensor]:
        # Decode all prompts and responses to strings
        prompts = [
            self._custom_tokenizer.decode(q_ids, skip_special_tokens=True)
            for q_ids in queries
        ]
        responses_text = [
            self._custom_tokenizer.decode(r_ids, skip_special_tokens=True)
            for r_ids in responses
        ]
        # Prepare ad text blocks: use the same batch ad_texts from generation if available
        if hasattr(self, '_last_batch_ad_texts'):
            ad_texts = self._last_batch_ad_texts
        else:
            ad_texts = []
            # Use dataset_idx from the batch, not batch index
            dataset_idxs = getattr(self, '_last_batch_dataset_idxs', list(range(len(prompts))))
            for i, idx in enumerate(dataset_idxs):
                if idx < len(self.ad_facts_list):
                    ad = self.ad_facts_list[idx]
                    ad_texts.append(
                        f"Product: {ad['ad_product']}\n"
                        f"Brand: {ad['brand']}\n"
                        f"URL: {ad['url']}\n"
                        f"Description: {ad['ad_description']}"
                    )
                else:
                    logger.warning(f"Dataset index {idx} out of range for ad_facts_list (len={len(self.ad_facts_list)})")
                    ad_texts.append("")
        # Extract no-ad responses from buffer for detectability
        # Ensure we have enough no-ad responses
        if len(PPO_NO_AD_BUFFER) < len(responses_text):
            logger.warning(f"⚠️ Not enough no-ad responses in buffer ({len(PPO_NO_AD_BUFFER)} < {len(responses_text)}). Using empty strings.")
        no_ads = [
            PPO_NO_AD_BUFFER.pop(0) if PPO_NO_AD_BUFFER else ""
            for _ in responses_text
        ]

        # Batch all async judge calls
        async def batch_judge():
            sc_tasks = [judge_coherence_async(p, r) for p, r in zip(prompts, responses_text)]
            sh_tasks = [judge_helpfulness_async(p, r) for p, r in zip(prompts, responses_text)]
            ss_tasks = [
                judge_ad_salience_async(p, r, ad_text)
                for p, r, ad_text in zip(prompts, responses_text, ad_texts)
            ]
            det_tasks = [judge_detectability_async(r, na) for r, na in zip(responses_text, no_ads)]
            return await asyncio.gather(
                asyncio.gather(*sc_tasks),
                asyncio.gather(*sh_tasks),
                asyncio.gather(*ss_tasks),
                asyncio.gather(*det_tasks),
            )

        sc_list, sh_list, ss_list, det_list = asyncio.run(batch_judge())
        scores = []
        # Aggregate results and log
        for i, (prompt, response, sc, sh, ss, det) in enumerate(
            zip(prompts, responses_text, sc_list, sh_list, ss_list, det_list)
        ):
            # Extract alignment for logging
            idx = self._last_batch_dataset_idxs[i]
            user_query = self._last_batch_raw_qs[i]
            ad_info = self.ad_facts_list[idx]
            # Debug: show raw query instead of full prompt
            logger.info(f"➡️ Item {i} Query: {user_query}")
            logger.info(f"➡️ Item {i} Ad info: {ad_texts[i]}")
            logger.info(f"➡️ Item {i} Generated with-ad response: {response}")
            logger.info(f"➡️ Item {i} Generated no-ad response: {no_ads[i]}")
            # Log individual judge scores for debugging
            logger.info(
                f"🧐 Judge details for item {i}: "
                f"Coherence={sc.get('Coherence Score', 0)}, "
                f"Helpfulness={sh.get('H1', 0)}, "
                f"Ad Salience={ss.get('Ad Salience Score', 0)}, "
                f"Detectability={det.get('detectability_cosine', 0)}"
            )
            # Detailed subscores and explanations
            logger.info(
                f"   Coherence subscores: C1={sc.get('C1', 0)}, C2={sc.get('C2', 0)}, C3={sc.get('C3', 0)}, C4={sc.get('C4', 0)}; Explanation: {sc.get('Coherence Explanation', '')}"
            )
            logger.info(
                f"   Helpfulness subscore: H1={sh.get('H1', 0)}; Explanation: {sh.get('Helpfulness Explanation', '')}"
            )
            logger.info(
                f"   Ad Salience subscores: S1={ss.get('S1', 0)}, S2={ss.get('S2', 0)}, S3={ss.get('S3', 0)}; Explanation: {ss.get('Ad Salience Explanation', '')}"
            )
            logger.info(
                f"   Detectability: detectability_cosine={det.get('detectability_cosine', None)}, similarity_cosine={det.get('similarity_cosine', None)}"
            )
            # Handle detectability score with None safety
            det_cos = det.get("detectability_cosine", 0)
            if det_cos is None:
                logger.warning(f"⚠️ Detectability score is None for item {i}, using 0")
                det_cos = 0
            det_cos = max(min(float(det_cos), 1.0), -1.0)  # Clamp between -1 and 1

            # Safely extract scores with defaults
            coherence_score = float(sc.get("Coherence Score", 0) or 0)
            helpfulness_score = float(sh.get("H1", 0) or 0)
            salience_score = float(ss.get("Ad Salience Score", 0) or 0)
            
            # IMPORTANT: Subtract detectability since lower is better (less detectable = better)
            # detectability_cosine ranges from -1 (very different) to 1 (very similar)
            # Lower detectability means the ad is less obvious, so we reward lower values
            total = coherence_score + helpfulness_score + salience_score - det_cos
            scores.append(torch.tensor(total, device=self.current_device))
            logger.info(f"✅ Judges complete for item {i}, total reward: {total:.4f} (coherence={coherence_score:.2f}, helpfulness={helpfulness_score:.2f}, salience={salience_score:.2f}, detectability_penalty={-det_cos:.4f})")

            TRAINING_LOGS.append({
                "query_idx": idx,
                "user_query": user_query,
                "ad_id": ad_info["ad_id"],
                "ad_product": ad_info["ad_product"],
                "brand": ad_info["brand"],
                "url": ad_info["url"],
                "ad_description": ad_info["ad_description"],
                "response_with_ad": response,
                "response_without_ad": no_ads[i],
                # Coherence subscores
                "C1": sc.get("C1", 0),
                "C2": sc.get("C2", 0),
                "C3": sc.get("C3", 0),
                "C4": sc.get("C4", 0),
                "coherence_score": sc.get("Coherence Score", 0),
                "coherence_explanation": sc.get("Coherence Explanation", ""),
                # Helpfulness
                "H1": sh.get("H1", 0),
                "helpfulness_explanation": sh.get("Helpfulness Explanation", ""),
                # Salience subscores
                "S1": ss.get("S1", 0),
                "S2": ss.get("S2", 0),
                "S3": ss.get("S3", 0),
                "salience_score": ss.get("Ad Salience Score", 0),
                "salience_explanation": ss.get("Ad Salience Explanation", ""),
                # Detectability
                "detectability_cosine": det.get("detectability_cosine", 0),
                "similarity_cosine": det.get("similarity_cosine", 0),
                # Total reward
                "total_reward": total,
            })
            logger.info(f"🧮 PPO reward distribution: {[r.item() for r in scores]}")
        return scores

    def compute_rewards(
        self,
        scores: torch.FloatTensor,
        logprobs: torch.FloatTensor,
        ref_logprobs: torch.FloatTensor,
        masks: torch.LongTensor,
    ):
        """
        Override compute_rewards to ensure device consistency and allow penalty customization.
        
        Args:
            scores: Reward scores from judges, shape (batch_size)
            logprobs: Log probabilities from policy model, shape (batch_size, response_length)
            ref_logprobs: Log probabilities from reference model, shape (batch_size, response_length)
            masks: Attention masks, shape (batch_size, response_length)
        
        Returns:
            rewards: Per-token rewards, shape (batch_size, response_length)
            non_score_reward: KL penalty per token, shape (batch_size, response_length)
            kls: KL divergence per token, shape (batch_size, response_length)
        """
        import torch
        
        # CRITICAL: Ensure all tensors are on the same device
        # Get device from logprobs (policy model output, should be on CUDA)
        target_device = logprobs.device
        
        # Move ref_logprobs to same device as logprobs if needed
        if ref_logprobs.device != target_device:
            ref_logprobs = ref_logprobs.to(target_device)
        
        # Move scores and masks to same device if needed
        if scores.device != target_device:
            scores = scores.to(target_device)
        if masks.device != target_device:
            masks = masks.to(target_device)
        
        # Call parent's compute_rewards with device-consistent tensors
        # This will compute: rewards = scores - kl_penalty_coef * kl_penalty
        rewards, non_score_reward, kls = super().compute_rewards(
            scores=scores,
            logprobs=logprobs,
            ref_logprobs=ref_logprobs,
            masks=masks,
        )
        
        # Log KL penalty statistics for monitoring
        # non_score_reward is the KL penalty per token (negative because it's subtracted)
        # kls is the raw KL divergence per token
        if kls.numel() > 0:
            # Get KL penalty coefficient from config (default 0.1)
            kl_coef = getattr(self.config, 'kl_penalty_coef', 0.1) if hasattr(self, 'config') else 0.1
            
            # Compute statistics (only for non-masked tokens)
            masked_kls = kls[masks.bool()]
            if masked_kls.numel() > 0:
                mean_kl = masked_kls.mean().item()
                max_kl = masked_kls.max().item()
                mean_kl_penalty = (-non_score_reward[masks.bool()]).mean().item()  # non_score_reward is negative
                
                # Log every few steps to avoid spam
                if not hasattr(self, '_kl_log_counter'):
                    self._kl_log_counter = 0
                self._kl_log_counter += 1
                
                if self._kl_log_counter % 10 == 1:  # Log every 10th call
                    logger.info(
                        f"📊 KL Penalty Stats: mean_kl={mean_kl:.4f}, max_kl={max_kl:.4f}, "
                        f"mean_penalty={mean_kl_penalty:.4f}, kl_coef={kl_coef:.3f}"
                    )
        
        return rewards, non_score_reward, kls

    def batched_forward_pass(self, model, queries, responses, model_inputs, return_logits=False, response_masks=None):
        """
        Override batched_forward_pass to ensure model output is converted to tuple format.
        The parent class expects (logits, past_key_values, values) but our model returns ModelOutput.
        Matches parent class signature exactly: (self, model, queries, responses, model_inputs, return_logits=False, response_masks=None)
        """
        # Ensure model is patched before calling parent's batched_forward_pass
        # The parent will call model(**input_kwargs, return_dict=True, use_cache=False)
        # and expects a 3-tuple, but our model returns ModelOutput
        if model is not None:
            # Get unwrapped model
            if hasattr(self, 'accelerator'):
                unwrapped_model = self.accelerator.unwrap_model(model)
            else:
                unwrapped_model = model
            
            # CRITICAL: Apply patch if not already patched
            # The model passed here might be a different instance or wrapped differently
            if not hasattr(unwrapped_model, '_patched_forward_log_count'):
                logger.warning("⚠️ Model not patched in batched_forward_pass, applying patch now...")
                import types
                original_forward = unwrapped_model.forward
                original_call = unwrapped_model.__call__
                
                # Use the same patching logic as in __init__
                def make_patched_forward_local(original_forward_func):
                    def patched_forward(self, *args, **kwargs):
                        # Extract return_dict from kwargs (default True for llamafactory)
                        return_dict = kwargs.pop('return_dict', True)
                        
                        # Call original forward
                        if isinstance(original_forward_func, types.MethodType):
                            original_output = original_forward_func(*args, return_dict=return_dict, **kwargs)
                        else:
                            original_output = original_forward_func(self, *args, return_dict=return_dict, **kwargs)
                        
                        # Convert ModelOutput to tuple format expected by llamafactory
                        if hasattr(original_output, "logits"):
                            # ModelOutput object - extract logits, past_key_values, and value
                            logits = original_output.logits
                            past_key_values = getattr(original_output, "past_key_values", None)
                            
                            # Try to get value from value head (for PPO models)
                            value = None
                            if hasattr(original_output, "value"):
                                value_attr = getattr(original_output, "value", None)
                                # Check if it's actually data (not a method)
                                if value_attr is not None and not callable(value_attr):
                                    value = value_attr
                            elif hasattr(original_output, "values"):
                                values_attr = getattr(original_output, "values", None)
                                # Check if it's actually data (not a method)
                                if values_attr is not None and not callable(values_attr):
                                    if isinstance(values_attr, (list, tuple)) and len(values_attr) > 0:
                                        value = values_attr[0]
                                    elif not isinstance(values_attr, (list, tuple)):
                                        value = values_attr
                            # Try to get value from model's value head if available
                            # For AutoModelForCausalLMWithValueHead, the value head is at self.v_head
                            if value is None:
                                # Check if model has v_head
                                has_v_head = hasattr(self, 'v_head') and self.v_head is not None
                                if not has_v_head:
                                    # Try to access via pretrained_model if it's wrapped
                                    if hasattr(self, 'pretrained_model') and hasattr(self.pretrained_model, 'v_head'):
                                        v_head = self.pretrained_model.v_head
                                        has_v_head = v_head is not None
                                    else:
                                        v_head = None
                                else:
                                    v_head = self.v_head
                                
                                if has_v_head and v_head is not None:
                                    try:
                                        # Try to get hidden states from output
                                        last_hidden = None
                                        if hasattr(original_output, "hidden_states") and original_output.hidden_states:
                                            hidden_states = original_output.hidden_states[-1] if isinstance(original_output.hidden_states, (list, tuple)) else original_output.hidden_states
                                            if hidden_states is not None:
                                                last_hidden = hidden_states
                                        elif hasattr(original_output, "last_hidden_state"):
                                            last_hidden = original_output.last_hidden_state
                                        
                                        if last_hidden is not None:
                                            # Value head expects [batch_size, seq_len, hidden_size]
                                            # We need to take the mean over sequence length or use the last token
                                            # For PPO, typically we use the last token's hidden state
                                            if len(last_hidden.shape) == 3:  # [batch, seq, hidden]
                                                # Use mean pooling or last token - try mean first
                                                pooled = last_hidden.mean(dim=1)  # [batch, hidden]
                                                value = v_head(pooled)  # [batch, 1] or [batch]
                                            else:
                                                # Already pooled or different shape
                                                value = v_head(last_hidden)
                                    except Exception as e:
                                        logger.warning(f"Could not compute value from value head: {e}")
                                        import traceback
                                        logger.debug(traceback.format_exc())
                                
                                # CRITICAL: If value is still None, create a zero tensor as fallback
                                # The parent class expects a tensor, not None (it tries to torch.cat values)
                                if value is None:
                                    import torch
                                    batch_size = logits.shape[0]
                                    seq_len = logits.shape[1] if logits.dim() > 1 else 1
                                    value = torch.zeros(batch_size, seq_len, device=logits.device, dtype=logits.dtype)
                                    if not hasattr(self, '_patched_forward_log_count') or self._patched_forward_log_count <= 3:
                                        logger.warning(f"⚠️ Value is None, creating zero tensor with shape {value.shape} as fallback")
                            
                            # Ensure value shape matches what LlamaFactory expects: [batch, seq_len]
                            if value is not None:
                                import torch
                                if isinstance(value, torch.Tensor):
                                    if value.dim() == 1:
                                        # [batch] -> [batch, seq_len]
                                        seq_len = logits.shape[1] if logits.dim() > 1 else 1
                                        value = value.unsqueeze(1).expand(-1, seq_len)
                                    elif value.dim() == 2 and value.shape[1] == 1 and logits.dim() > 1:
                                        # [batch, 1] -> [batch, seq_len]
                                        seq_len = logits.shape[1]
                                        value = value.expand(-1, seq_len)
                            
                            result = (logits, past_key_values, value)
                            # Track patch usage
                            if not hasattr(self, '_patched_forward_log_count'):
                                self._patched_forward_log_count = 0
                            self._patched_forward_log_count += 1
                            if self._patched_forward_log_count <= 3:
                                logger.info(f"🔧 patched_forward (batched_forward_pass) returning: logits shape={original_output.logits.shape if hasattr(original_output.logits, 'shape') else 'N/A'}, value={value is not None}")
                            return result
                        elif isinstance(original_output, tuple):
                            # Already a tuple, pad to 3 elements if needed
                            if len(original_output) >= 3:
                                return original_output[:3]
                            else:
                                return (original_output + (None,) * 3)[:3]
                        elif isinstance(original_output, dict):
                            # Dict output
                            logits = original_output.get("logits", None)
                            past_key_values = original_output.get("past_key_values", None)
                            value = original_output.get("value", original_output.get("values", None))
                            return logits, past_key_values, value
                        else:
                            logger.warning(f"⚠️ Unexpected model output type: {type(original_output)}")
                            return (original_output, None, None)
                    return patched_forward
                
                def make_patched_call_local(patched_forward_func):
                    def patched_call(self, *args, **kwargs):
                        return patched_forward_func(self, *args, **kwargs)
                    return patched_call
                
                patched_forward_local = types.MethodType(make_patched_forward_local(original_forward), unwrapped_model)
                patched_call_local = types.MethodType(make_patched_call_local(patched_forward_local), unwrapped_model)
                unwrapped_model.forward = patched_forward_local
                unwrapped_model.__call__ = patched_call_local
                unwrapped_model._patched_forward_log_count = 0  # Mark as patched
                logger.info("✅ Applied forward/__call__ patch to model in batched_forward_pass")
        
        # CRITICAL: Ensure all inputs are on the correct device
        # The parent class will use these directly, so they must be on the same device as the model
        import torch
        
        # Get model device from the passed model (unwrap if needed) to avoid mismatches
        if model is not None:
            target_model = self.accelerator.unwrap_model(model) if hasattr(self, 'accelerator') and self.accelerator is not None else model
            if hasattr(target_model, 'device'):
                model_device = target_model.device
            else:
                model_device = next(target_model.parameters()).device
        else:
            # Fallback to self.model if model is None
            model_device = next(self.model.parameters()).device
        
        # Move queries to model device (if tensors)
        if queries is not None:
            device_fixed_queries = []
            for q in queries:
                if isinstance(q, torch.Tensor):
                    device_fixed_queries.append(q.to(model_device))
                else:
                    device_fixed_queries.append(q)
            queries = device_fixed_queries
        
        # Move responses to model device (if tensors)
        if responses is not None:
            device_fixed_responses = []
            for r in responses:
                if isinstance(r, torch.Tensor):
                    device_fixed_responses.append(r.to(model_device))
                else:
                    device_fixed_responses.append(r)
            responses = device_fixed_responses
        
        # Move all tensors in model_inputs to the model device
        if model_inputs is not None and isinstance(model_inputs, dict):
            device_fixed_inputs = {}
            for key, value in model_inputs.items():
                if isinstance(value, torch.Tensor):
                    device_fixed_inputs[key] = value.to(model_device)
                elif isinstance(value, (list, tuple)):
                    # Handle lists/tuples of tensors
                    device_fixed_list = []
                    for item in value:
                        if isinstance(item, torch.Tensor):
                            device_fixed_list.append(item.to(model_device))
                        else:
                            device_fixed_list.append(item)
                    device_fixed_inputs[key] = type(value)(device_fixed_list)
                else:
                    device_fixed_inputs[key] = value
            model_inputs = device_fixed_inputs
        
        # Call parent's batched_forward_pass - the patched forward/__call__ should handle the conversion
        # Pass through all arguments exactly as parent expects
        result = super().batched_forward_pass(model, queries, responses, model_inputs, return_logits=return_logits, response_masks=response_masks)
        
        # CRITICAL: If any tensors in result are on CPU (from reference model), move them to policy model's device
        # This ensures ref_logprobs are on the same device as logprobs for reward computation
        if hasattr(self, 'model'):
            # Get policy model device
            try:
                policy_device = next(self.model.parameters()).device
            except StopIteration:
                policy_device = torch.device('cuda:0')  # Fallback
            
            # Only move if policy is on CUDA and result contains CPU tensors
            if str(policy_device) != 'cpu' and isinstance(result, tuple):
                def move_to_device(obj, device):
                    """Recursively move tensors to device"""
                    if isinstance(obj, torch.Tensor):
                        if str(obj.device) == 'cpu':
                            return obj.to(device)
                        return obj
                    elif isinstance(obj, (list, tuple)):
                        return type(obj)(move_to_device(item, device) for item in obj)
                    else:
                        return obj
                
                # Check if any tensor is on CPU
                has_cpu_tensors = False
                for item in result:
                    if isinstance(item, torch.Tensor) and str(item.device) == 'cpu':
                        has_cpu_tensors = True
                        break
                    elif isinstance(item, (list, tuple)):
                        for subitem in item:
                            if isinstance(subitem, torch.Tensor) and str(subitem.device) == 'cpu':
                                has_cpu_tensors = True
                                break
                        if has_cpu_tensors:
                            break
                
                if has_cpu_tensors:
                    result = tuple(move_to_device(item, policy_device) for item in result)
        
        return result

    def ppo_train(self, resume_from_checkpoint=None, start_step=0, start_query_idx=0):
        # Clear GPU cache at start to free up memory
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
            torch.cuda.synchronize()
            total_mem = torch.cuda.get_device_properties(0).total_memory
            allocated_mem = torch.cuda.memory_allocated(0)
            free_mem = (total_mem - allocated_mem) / 1e9  # Convert bytes to GB
            print(f"🧹 Cleared GPU cache. Free memory: {free_mem:.2f} GB")
        
        print("✅ USING CUSTOM ppo_train!")
        print(f"📊 Resume info: checkpoint={resume_from_checkpoint}, step={start_step}, query_idx={start_query_idx}")

        total_loss = 0.0
        total_reward = 0.0
        total_steps = 0
        
        # Calculate total steps for progress tracking
        total_epochs = self.finetuning_args.ppo_epochs
        batches_per_epoch = len(self.dataloader)
        total_batches = total_epochs * batches_per_epoch
        
        print(f"📈 Training plan: {total_epochs} epochs × {batches_per_epoch} batches = {total_batches} total batches")
        print(f"⏰ Started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

        # Reset dataloader at the start of training
        self._reset_dataloader()
        
        # Time tracking
        training_start_time = time.time()
        step_times = []
        
        # Track current step for checkpoint saving
        self._current_step = start_step
        self.total_steps = 0  # Track total completed steps

        # If resuming, calculate which epoch and batch to start from
        start_epoch = 0
        start_batch_idx = 0
        if start_step > 0:
            start_epoch = start_step // batches_per_epoch
            start_batch_idx = start_step % batches_per_epoch
            print(f"⏯ Resuming from step {start_step} (epoch {start_epoch + 1}, batch {start_batch_idx + 1})")
            # Skip batches in the dataloader to get to the right position
            if start_batch_idx > 0:
                # Reset and skip to the right position
                self._reset_dataloader()
                for _ in range(start_batch_idx):
                    try:
                        next(self._dataloader_iter)
                    except StopIteration:
                        self._reset_dataloader()
                        break

        for epoch in range(start_epoch, self.finetuning_args.ppo_epochs):
            print(f"\n{'='*60}")
            print(f"📚 EPOCH {epoch + 1}/{total_epochs}")
            print(f"{'='*60}")
            
            # Determine starting batch index for this epoch
            batch_start = start_batch_idx if epoch == start_epoch else 0
            
            for batch_idx in range(batch_start, batches_per_epoch):
                step = epoch * batches_per_epoch + batch_idx
                step_start_time = time.time()
                
                try:
                    batch = self._make_batch()
                    if not batch:
                        print(f"⚠️ Skipping step {step}: empty batch")
                        continue

                    # Progress indicator
                    progress = (step + 1) / total_batches * 100
                    print(f"\n🔁 Step {step + 1}/{total_batches} ({progress:.1f}%) | Epoch {epoch + 1}/{total_epochs} | Batch {batch_idx + 1}/{batches_per_epoch}")
                    print(f"⏱️  Time: {datetime.now().strftime('%H:%M:%S')}")
                    
                    self.model.eval()
                    
                    # Batch from dataloader contains lists (raw data), not tensors
                    # No need to move to device - get_inputs will handle tokenization and device placement
                    
                    print("  📝 Generating responses...")
                    gen_start = time.time()
                    queries, responses = self.get_inputs(batch)
                    gen_time = time.time() - gen_start
                    print(f"  ✅ Generation complete ({gen_time:.1f}s)")
                    
                    print("  🧐 Calling judges...")
                    judge_start = time.time()
                    rewards = self.get_rewards(queries, responses)
                    judge_time = time.time() - judge_start
                    print(f"  ✅ Judging complete ({judge_time:.1f}s)")

                    if not rewards:
                        print(f"  ⚠️ No rewards returned, skipping optimization")
                        continue

                    print("  🔄 Updating model...")
                    self.model.train()
                    update_start = time.time()
                    stats = self.step(queries, responses, rewards)
                    update_time = time.time() - update_start

                    step_loss = float(stats.get("ppo/loss/total", 0.0))
                    step_reward = torch.stack(rewards).mean().item()

                    total_loss += step_loss
                    total_reward += step_reward
                    total_steps += 1
                    self.total_steps = total_steps  # Update for interruption handling
                    self._current_step = step + 1  # Update current step
                    
                    step_time = time.time() - step_start_time
                    step_times.append(step_time)
                    
                    # Calculate ETA
                    avg_step_time = sum(step_times[-10:]) / min(10, len(step_times))  # Average of last 10 steps
                    remaining_steps = total_batches - (step + 1)
                    eta_seconds = avg_step_time * remaining_steps
                    eta = timedelta(seconds=int(eta_seconds))

                    print(f"  ✅ Step complete — Loss: {step_loss:.4f}, Reward: {step_reward:.4f}")
                    print(f"  ⏱️  Step time: {step_time:.1f}s (Gen: {gen_time:.1f}s, Judge: {judge_time:.1f}s, Update: {update_time:.1f}s)")
                    print(f"  📊 Avg step time: {avg_step_time:.1f}s | ETA: {eta}")
                    print(f"  📈 Progress: {len(TRAINING_LOGS)} total judge entries")
                    
                    # Save logs incrementally every 50 steps to avoid losing progress
                    if (step + 1) % 50 == 0:
                        try:
                            log_path = Path(self.training_args.output_dir) / "ppo_judging_log.csv"
                            pd.DataFrame(TRAINING_LOGS).to_csv(log_path, index=False)
                            elapsed = time.time() - training_start_time
                            elapsed_str = str(timedelta(seconds=int(elapsed)))
                            print(f"  💾 Saved incremental logs: {len(TRAINING_LOGS)} entries | Elapsed: {elapsed_str}")
                        except Exception as e:
                            logger.warning(f"⚠️ Failed to save incremental logs: {e}")
                    
                    # Save model checkpoint every 100 steps (configurable via save_steps)
                    save_steps = getattr(self.training_args, 'save_steps', 100)
                    if (step + 1) % save_steps == 0:
                        try:
                            print(f"  💾 Saving checkpoint at step {step + 1}...")
                            # Save using trainer's save_model which creates checkpoint-* directories
                            checkpoint_dir = Path(self.training_args.output_dir) / f"checkpoint-{step + 1}"
                            checkpoint_dir.mkdir(parents=True, exist_ok=True)
                            
                            # Save model and tokenizer
                            self.model.save_pretrained(checkpoint_dir)
                            if hasattr(self, '_custom_tokenizer') and self._custom_tokenizer:
                                self._custom_tokenizer.save_pretrained(checkpoint_dir)
                            
                            # Save optimizer state if available
                            if hasattr(self, 'optimizer') and self.optimizer:
                                torch.save(self.optimizer.state_dict(), checkpoint_dir / "optimizer.pt")
                            
                            # Save training position
                            last_pos = {"query_index": step + 1}
                            with open(Path(self.training_args.output_dir) / "last_query_position.json", "w") as f:
                                json.dump(last_pos, f)
                            
                            print(f"  ✅ Checkpoint saved to {checkpoint_dir}")
                        except Exception as e:
                            logger.warning(f"⚠️ Failed to save checkpoint: {e}")
                            import traceback
                            traceback.print_exc()

                except Exception as e:
                    print(f"  ❌ Step {step} failed due to: {e}")
                    import traceback
                    traceback.print_exc()
                    print("❌ Exiting due to error in PPO training")
                    sys.exit(1)

        if total_steps > 0:
            avg_loss = total_loss / total_steps
            avg_reward = total_reward / total_steps
            total_time = time.time() - training_start_time
            total_time_str = str(timedelta(seconds=int(total_time)))
            print(f"\n{'='*60}")
            print(f"🏁 PPO Training Complete!")
            print(f"{'='*60}")
            print(f"📊 Total steps: {total_steps}")
            print(f"📈 Avg Loss: {avg_loss:.4f}")
            print(f"🎯 Avg Reward: {avg_reward:.4f}")
            print(f"⏱️  Total time: {total_time_str}")
            print(f"💾 Total judge entries: {len(TRAINING_LOGS)}")
            print(f"{'='*60}\n")
        else:
            print("❌ PPO training ended with 0 valid steps.")
            sys.exit(1)

def make_trainer(
    model_name: str,
    hf_token: str,
    data_path: str,
    ad_facts_list: List[dict],
):
    global GLOBAL_AD_FACTS_LIST
    GLOBAL_AD_FACTS_LIST = ad_facts_list

    # --- Load the tokenizer ---
    tokenizer = AutoTokenizer.from_pretrained(
        model_name, use_fast=True, trust_remote_code=True, token=hf_token
    )

    # ✅ Configure tokenizer once
    tokenizer.padding_side = "left"
    tokenizer.truncation_side = "right"
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token or tokenizer.unk_token
    tokenizer.pad_token_id = tokenizer.convert_tokens_to_ids(tokenizer.pad_token)

    # --- Load the policy (with value head) ---
    device_str = "GPU" if torch.cuda.is_available() else "CPU"
    logger.info(f"💻 Loading model for {device_str} training...")
    try:
        if torch.cuda.is_available():
            # Use float16 on GPU for speed and memory efficiency
            # NOTE: Cannot use device_map="auto" with ValueHead models (they don't support CPU/disk offloading)
            # Try device_map="cuda:0" first (forces GPU, no offloading)
            # If that fails, fall back to loading to CPU then moving to GPU
            try:
                logger.info("📥 Loading model directly to GPU (device_map='cuda:0')...")
                policy = AutoModelForCausalLMWithValueHead.from_pretrained(
                    model_name,
                    trust_remote_code=True,
                    token=hf_token,  # Use 'token' instead of deprecated 'use_auth_token'
                    torch_dtype=torch.float16,  # Use float16 on GPU
                    device_map="cuda:0",  # Force GPU, no offloading
                    low_cpu_mem_usage=True,  # Reduce memory usage during loading
                )
                logger.info("✅ Model loaded directly to GPU")
            except (RuntimeError, ValueError) as e:
                if "out of memory" in str(e).lower() or "offload" in str(e).lower():
                    logger.warning(f"⚠️ Direct GPU loading failed: {e}")
                    logger.info("📥 Falling back to CPU loading then GPU move...")
                    # Fallback: load to CPU first, then move to GPU
                    policy = AutoModelForCausalLMWithValueHead.from_pretrained(
                        model_name,
                        trust_remote_code=True,
                        token=hf_token,  # Use 'token' instead of deprecated 'use_auth_token'
                        torch_dtype=torch.float16,
                        device_map=None,  # Load to CPU
                        low_cpu_mem_usage=True,
                    )
                    logger.info("🚀 Moving model to GPU...")
                    policy = policy.to("cuda")
                    logger.info("✅ Model loaded and moved to GPU")
                else:
                    raise
        else:
            # Use float32 on CPU
            policy = AutoModelForCausalLMWithValueHead.from_pretrained(
                model_name,
                trust_remote_code=True,
                token=hf_token,  # Use 'token' instead of deprecated 'use_auth_token'
                torch_dtype=torch.float32,  # CPU mode
                device_map=None,
            ).to(DEVICE)
        logger.info(f"💻 Model loaded on {DEVICE}")
    except Exception as e:
        logger.error(f"❌ Failed to load model: {e}")
        raise e

    # Patch model forward (__call__) for llamafactory PPO trainer
    # This ensures the model always returns (logits, past_key_values, value) tuple
    import types
    
    # Store original methods
    original_forward_policy = policy.forward
    original_call_policy = policy.__call__
    
    def make_patched_forward(original_forward_func):
        """Create a patched forward method that converts ModelOutput to tuple."""
        def patched_forward(self, *args, **kwargs):
            # Extract return_dict from kwargs (default True for llamafactory)
            return_dict = kwargs.pop('return_dict', True)
            
            # Call the original forward method
            # original_forward_func is a bound method, so we can call it directly
            # But we need to make sure it's called with the right self
            if isinstance(original_forward_func, types.MethodType):
                # It's already a bound method, call it directly
                original_output = original_forward_func(*args, return_dict=return_dict, **kwargs)
            else:
                # It's an unbound method, call with self
                original_output = original_forward_func(self, *args, return_dict=return_dict, **kwargs)
            
            # Debug: log output type (only first few times to avoid spam)
            if not hasattr(self, '_patched_forward_log_count'):
                self._patched_forward_log_count = 0
            if self._patched_forward_log_count < 3:
                logger.info(f"🔧 patched_forward output type: {type(original_output)}, has logits: {hasattr(original_output, 'logits')}, has value: {hasattr(original_output, 'value')}")
                # Check all attributes
                if hasattr(original_output, '__dict__'):
                    logger.info(f"🔧 patched_forward output keys: {list(original_output.__dict__.keys())[:10]}")
                elif hasattr(original_output, '__class__'):
                    logger.info(f"🔧 patched_forward output class: {original_output.__class__.__name__}")
                self._patched_forward_log_count += 1
            
            # Handle ModelOutput object (when return_dict=True)
            if hasattr(original_output, "logits"):
                logits = original_output.logits
                past_key_values = getattr(original_output, "past_key_values", None)
                # For ValueHead models, check for value in the output
                # The value might be in the output directly or as an attribute
                value = None
                if hasattr(original_output, "value"):
                    value = original_output.value
                elif hasattr(original_output, "values"):  # Sometimes it's "values" (plural)
                    values_attr = getattr(original_output, "values", None)
                    # Check if it's actually data (not a method like dict.values())
                    if values_attr is not None and not callable(values_attr):
                        if isinstance(values_attr, (list, tuple)) and len(values_attr) > 0:
                            value = values_attr[0]
                        elif not isinstance(values_attr, (list, tuple)):
                            value = values_attr
                elif isinstance(original_output, dict) and "value" in original_output:
                    value = original_output["value"]
                elif isinstance(original_output, dict) and "values" in original_output:
                    values = original_output["values"]
                    # Check if it's actually data (not a method)
                    if values is not None and not callable(values):
                        if isinstance(values, (list, tuple)) and len(values) > 0:
                            value = values[0]
                        elif not isinstance(values, (list, tuple)):
                            value = values
                
                # If value is still None, try to get it from hidden states via value head
                if value is None:
                    # Check if model has v_head
                    has_v_head = hasattr(self, 'v_head') and self.v_head is not None
                    if not has_v_head:
                        # Try to access via pretrained_model if it's wrapped
                        if hasattr(self, 'pretrained_model') and hasattr(self.pretrained_model, 'v_head'):
                            v_head = self.pretrained_model.v_head
                            has_v_head = v_head is not None
                        else:
                            v_head = None
                    else:
                        v_head = self.v_head
                    
                    if has_v_head and v_head is not None and hasattr(original_output, 'hidden_states'):
                        try:
                            # Get last hidden state
                            hidden_states = original_output.hidden_states[-1] if isinstance(original_output.hidden_states, (list, tuple)) else original_output.hidden_states
                            if hidden_states is not None:
                                # Value head expects specific input format
                                if len(hidden_states.shape) == 3:  # [batch, seq, hidden]
                                    pooled = hidden_states.mean(dim=1)  # [batch, hidden]
                                    value = v_head(pooled)  # [batch, 1] or [batch]
                                    if len(value.shape) > 1 and value.shape[-1] == 1:
                                        value = value.squeeze(-1)
                                else:
                                    value = v_head(hidden_states).squeeze(-1)
                        except Exception as e:
                            logger.debug(f"Could not compute value from value head: {e}")
                    
                    # CRITICAL: If value is still None, create a zero tensor as fallback
                    # The parent class expects a tensor, not None (it tries to torch.cat values)
                    if value is None:
                        import torch
                        batch_size = logits.shape[0]
                        seq_len = logits.shape[1] if logits.dim() > 1 else 1
                        value = torch.zeros(batch_size, seq_len, device=logits.device, dtype=logits.dtype)
                        if self._patched_forward_log_count <= 3:
                            logger.warning(f"⚠️ Value is None, creating zero tensor with shape {value.shape} as fallback")
                
                # Ensure value shape matches what LlamaFactory expects: [batch, seq_len]
                if value is not None:
                    import torch
                    if isinstance(value, torch.Tensor):
                        if value.dim() == 1:
                            # [batch] -> [batch, seq_len]
                            seq_len = logits.shape[1] if logits.dim() > 1 else 1
                            value = value.unsqueeze(1).expand(-1, seq_len)
                        elif value.dim() == 2 and value.shape[1] == 1 and logits.dim() > 1:
                            # [batch, 1] -> [batch, seq_len]
                            seq_len = logits.shape[1]
                            value = value.expand(-1, seq_len)
                
                result = (logits, past_key_values, value)
                if self._patched_forward_log_count <= 3:
                    logger.info(f"🔧 patched_forward returning: logits shape={original_output.logits.shape if hasattr(original_output.logits, 'shape') else 'N/A'}, value={value is not None if value is not None else 'None'}")
                return result
            # Handle tuple output (when return_dict=False)
            elif isinstance(original_output, tuple):
                # If it's already a tuple, pad to 3 elements if needed
                if len(original_output) >= 3:
                    return original_output[:3]
                else:
                    return (original_output + (None,) * 3)[:3]
            # Handle dict output
            elif isinstance(original_output, dict):
                logits = original_output.get("logits", None)
                past_key_values = original_output.get("past_key_values", None)
                value = original_output.get("value", original_output.get("values", None))
                return logits, past_key_values, value
            # Fallback: if it's a single value, wrap it
            else:
                logger.warning(f"⚠️ Unexpected model output type: {type(original_output)}, dir: {dir(original_output)[:10]}")
                # Try to extract logits if it's a ModelOutput-like object
                if hasattr(original_output, '__dict__'):
                    attrs = original_output.__dict__
                    logits = attrs.get('logits', None)
                    value = attrs.get('value', attrs.get('values', None))
                    if logits is not None:
                        return logits, None, value
                # Last resort: return as tuple with None placeholders
                logger.error(f"❌ Cannot extract logits from output type {type(original_output)}")
                return original_output, None, None
        return patched_forward
    
    def make_patched_call(patched_forward_func):
        """Create a patched __call__ method that routes through patched_forward."""
        def patched_call(self, *args, **kwargs):
            # __call__ typically calls forward, so we route through patched_forward
            return patched_forward_func(self, *args, **kwargs)
        return patched_call
    
    # Create patched methods bound to policy
    patched_forward_policy = types.MethodType(make_patched_forward(original_forward_policy), policy)
    patched_call_policy = types.MethodType(make_patched_call(patched_forward_policy), policy)
    
    # Patch both forward and __call__ to ensure all code paths work
    policy.forward = patched_forward_policy
    policy.__call__ = patched_call_policy
    policy.gradient_checkpointing_enable()
    policy.config.pad_token_id = tokenizer.pad_token_id
    
    # Debug: Verify patch is applied
    logger.info(f"✅ Patched model forward method: {type(policy.forward)}")
    logger.info(f"✅ Patched model __call__ method: {type(policy.__call__)}")
    # Test the patch works
    try:
        test_input = tokenizer("test", return_tensors="pt").to(next(policy.parameters()).device)
        test_result = policy(**test_input, return_dict=True, use_cache=False)
        if isinstance(test_result, tuple) and len(test_result) == 3:
            logger.info(f"✅ Patch verification: Model returns tuple format correctly")
        else:
            logger.warning(f"⚠️ Patch verification FAILED: Model returns {type(test_result)}, length {len(test_result) if isinstance(test_result, (tuple, list)) else 'N/A'}")
    except Exception as e:
        logger.warning(f"⚠️ Patch verification test failed: {e}")

    # --- Frozen reference model ---
    # Always keep reference model on CPU to save GPU memory (it doesn't need gradients)
    ref = create_reference_model(policy)
    ref = ref.to("cpu")  # Always CPU to save GPU memory
    
    # Patch reference model with the same forward/call methods
    original_forward_ref = ref.forward
    patched_forward_ref = types.MethodType(make_patched_forward(original_forward_ref), ref)
    patched_call_ref = types.MethodType(make_patched_call(patched_forward_ref), ref)
    ref.forward = patched_forward_ref
    ref.__call__ = patched_call_ref
    
    ref.eval()
    for p in ref.parameters():
        p.requires_grad = False

    # --- Load dataset (keep in raw format, tokenization happens in collator) ---
    ds = load_dataset("csv", data_files={"train": data_path})["train"]
    ds = ds.add_column("dataset_idx", list(range(len(ds))))
    
    # Set format to python dicts (not Arrow) so our collator can work with it
    # Keep dataset in raw format - the collator will handle tokenization
    ds.set_format(type="python")  # Use python format, not torch or arrow

    # --- Collator (single source of truth) ---
    collator = PPODataCollator(tokenizer)

    # --- Trainer args ---
    model_args      = ModelArguments(model_name_or_path=model_name, hf_hub_token=hf_token)
    data_args       = DataArguments(
        template="default",
        dataset=Path(data_path).name,
        dataset_dir=str(Path(data_path).parent),
    )
    # Speed optimization: Allow configurable batch size and epochs via environment variables
    # Reduced GPU batch size from 8 to 4 to avoid OOM errors
    batch_size = int(os.getenv("PPO_BATCH_SIZE", "4" if torch.cuda.is_available() else "4"))
    ppo_epochs = int(os.getenv("PPO_EPOCHS", "2" if torch.cuda.is_available() else "1"))  # Reduced from 4
    max_new_tokens = int(os.getenv("MAX_NEW_TOKENS", "256" if torch.cuda.is_available() else "128"))  # Reduced from 512
    
    print(f"⚙️ Training config: batch_size={batch_size}, epochs={ppo_epochs}, max_new_tokens={max_new_tokens}")
    
    training_args   = TrainingArguments(
        output_dir="logs/ppo_run",
        per_device_train_batch_size=batch_size,
        save_strategy="steps",
        save_steps=100,  # Save less frequently to reduce I/O
        logging_steps=10,  # Log less frequently
        max_grad_norm=1.0,
        gradient_checkpointing=True,
        dataloader_num_workers=2 if torch.cuda.is_available() else 0,  # Enable workers on GPU
        no_cuda=not torch.cuda.is_available(),  # Auto-detect
        dataloader_pin_memory=torch.cuda.is_available(),  # Pin memory on GPU
    )
    finetuning_args = FinetuningArguments(
        ppo_epochs=ppo_epochs, 
        ppo_buffer_size=1,
        reward_model_type="api",  # Using custom get_rewards with API judges, not model-based
        ppo_target=0.1,  # Default KL divergence target for PPO
        ppo_score_norm=False,  # Disable score normalization (can enable if needed)
        ppo_whiten_rewards=False,  # Disable reward whitening (can enable if needed)
    )
    generating_args = GeneratingArguments(
        do_sample=False,
        temperature=None,
        top_k=None,
        top_p=None,
        max_new_tokens=max_new_tokens,
    )

    # --- Build trainer ---
    trainer = MyPPOTrainer(
        model_args      = model_args,
        training_args   = training_args,
        finetuning_args = finetuning_args,
        generating_args = generating_args,
        callbacks       = None,
        model           = policy,
        reward_model    = None,
        ref_model       = ref,
        tokenizer       = tokenizer,
        processor       = None,
        data_collator   = collator,
        train_dataset   = ds,
        ad_facts_list   = ad_facts_list,
    )

    # Expose args + objects
    trainer.data_args = data_args
    trainer.model_args = model_args
    trainer.training_args = training_args
    trainer.finetuning_args = finetuning_args
    trainer.generating_args = generating_args
    trainer.train_dataset = ds
    trainer.ref_model = ref
    trainer._custom_tokenizer = tokenizer  # still available, but collator is preferred
    
    # Now that train_dataset is set, initialize the dataloader if it wasn't done in __init__
    if trainer._dataloader_iter is None:
        trainer._reset_dataloader()

    return trainer

