import llamafactory.train.ppo.workflow as _wf
_wf.create_reward_model = lambda model, model_args, finetuning_args: None
from llamafactory.train.ppo.workflow import CustomPPOTrainer
import torch
import asyncio
import time
from typing import List, Optional
from datetime import datetime, timedelta
from llamafactory.hparams import (
    ModelArguments,
    DataArguments,
    FinetuningArguments,
    GeneratingArguments,
)
from transformers import TrainingArguments
from datasets import load_dataset
# Note: We're now using processing_class instead of deprecated tokenizer 
from transformers import AutoTokenizer, BitsAndBytesConfig
from trl import AutoModelForCausalLMWithValueHead, create_reference_model
from .prompts import get_prompt_with_ad, get_prompt_without_ad
from judge import (
    judge_coherence_async,
    judge_helpfulness_async,
    judge_ad_salience_async,
    judge_detectability_async,
)
from torch.utils.data import DataLoader
import pandas as pd
from pathlib import Path
import sys  # for handling interrupt and exit
import json
from config import DATA_FILE
import os
import types
from collections import deque
import math
import torch
from trl.core import logprobs_from_logits

# Note: We're now using processing_class instead of deprecated tokenizer
# No need to suppress warnings since we're not using the deprecated attribute
import logging
logging.basicConfig(format='%(asctime)s - %(levelname)s - %(message)s', level=logging.INFO)
logger = logging.getLogger(__name__)
# Global list to collect PPO judging logs
TRAINING_LOGS: List[dict] = []
# Buffer to store no-ad responses generated by PPO for detectability
PPO_NO_AD_BUFFER = deque(maxlen=100000)  # or some big cap
# Global ad facts list for custom PPO trainer
GLOBAL_AD_FACTS_LIST: List[dict] = []

# Auto-detect device (GPU if available, otherwise CPU)
# Set memory fragmentation optimization for CUDA
if torch.cuda.is_available():
    os.environ.setdefault("PYTORCH_ALLOC_CONF", "expandable_segments:True")
    DEVICE = torch.device("cuda")
    print(f"🚀 GPU detected: {torch.cuda.get_device_name(0)}")
    print(f"💾 GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
    print(f"🔧 CUDA memory optimization enabled")
else:
    DEVICE = torch.device("cpu")
    print("⚠️ No GPU detected, using CPU (training will be slower)")

# Define a custom collator to pad and retain metadata
class PPODataCollator:
    def __init__(self, tokenizer, max_length=512, ad_keys=None):
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.ad_keys = ad_keys or ["ad_product", "brand", "url", "ad_description"]
        self._call_count = 0  # Debug counter

        # Enforce padding strategy once
        self.tokenizer.padding_side = "left"
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token or self.tokenizer.unk_token
            self.tokenizer.pad_token_id = self.tokenizer.convert_tokens_to_ids(self.tokenizer.pad_token)

    def __call__(self, features):
        self._call_count += 1
        
        if not features:
            raise ValueError("❌ Empty features list provided to collator")
        
        # Convert Arrow format to dict if needed (datasets library returns Arrow format)
        if hasattr(features[0], 'keys'):
            # Already a dict-like object
            first_item = features[0]
        else:
            # Might be Arrow format, convert to dict
            first_item = dict(features[0]) if not isinstance(features[0], dict) else features[0]
            features = [dict(f) if not isinstance(f, dict) else f for f in features]
        
        if self._call_count <= 3:
            print(f"📦 Collating batch {self._call_count}: {list(first_item.keys()) if hasattr(first_item, 'keys') else type(first_item)}")

        # Check if this is a raw dataset item (has vague_query) or a prompt item (has text)
        if "text" in first_item:
            # Tokenize prompts (used in get_inputs)
            texts = [f.get("text", "") if isinstance(f, dict) else getattr(f, "text", "") for f in features]
            batch = self.tokenizer(
                texts,
                truncation=True,
                padding=True,
                max_length=self.max_length,
                return_tensors="pt",
            )
            # Preserve dataset_idx if present
            if "dataset_idx" in first_item:
                batch["dataset_idx"] = [f.get("dataset_idx") if isinstance(f, dict) else getattr(f, "dataset_idx", None) for f in features]
        else:
            # Raw dataset items - just preserve all fields without tokenization
            # The dataloader should pass raw items, tokenization happens in get_inputs
            batch = {}
            # Preserve all fields from the dataset
            keys = first_item.keys() if hasattr(first_item, 'keys') else []
            for key in keys:
                batch[key] = [
                    f.get(key, None) if isinstance(f, dict) else getattr(f, key, None)
                    for f in features
                ]

        if self._call_count <= 3:
            print(f"📦 Collated batch shapes: {[(k, (v.shape if hasattr(v, 'shape') else type(v))) for k, v in batch.items()]}")
        
        return batch

class MyPPOTrainer(CustomPPOTrainer):
    def __init__(
        self,
        *args,
        ad_facts_list: Optional[List[dict]] = None,
        **kwargs,
    ):
        
        custom_collator = kwargs.get('data_collator', None)
        
        
        train_dataset = kwargs.get('train_dataset', None)
        if train_dataset is not None:
            # Store original dataset length for verification
            original_len = len(train_dataset)
            logger.info(f"📊 Preserving train_dataset with {original_len} rows before parent __init__")
            
            
            self._original_train_dataset = train_dataset
            
            # NOTE: Do NOT add 'dataset' to kwargs - parent class doesn't accept it
            # The parent will get dataset from train_dataset and may filter it
        else:
            self._original_train_dataset = None
        ta = kwargs.get("training_args", None) or kwargs.get("args", None)
        if ta is not None:
            self.args = ta
                
        # Call super first to initialize self.args, self.tokenizer, etc.
        # The parent class will handle train_dataset from kwargs
        self._policy_with_vhead = kwargs.get("model", None)
        super().__init__(*args, **kwargs)
        self._ref_model = getattr(self, "_ref_model", None) or getattr(self, "ref_model", None)
        u = self.accelerator.unwrap_model(self.model)
        if not hasattr(u, "v_head") or u.v_head is None:
            logger.warning("⚠️ Parent replaced policy with base model (no v_head). Restoring ValueHead policy...")

            if self._policy_with_vhead is None:
                raise RuntimeError("No saved ValueHead policy to restore from.")

            # restore model
            self.model = self._policy_with_vhead

            # move model to accelerator device
            dev = self.accelerator.device
            self.model = force_valuehead_all_cuda(self.model, str(dev))

            # IMPORTANT: rebuild optimizer to match restored parameters
            lr = getattr(self.args, "learning_rate", 5e-5)
            wd = getattr(self.args, "weight_decay", 0.0)
            self.optimizer = torch.optim.AdamW(self.model.parameters(), lr=lr, weight_decay=wd)

            # prepare BOTH together so accelerate wraps consistently
            self.model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)

            # sanity print
            uu = self.accelerator.unwrap_model(self.model)
            bb = getattr(uu, "pretrained_model", uu)
            logger.info(
            f"✅ Restored base device: {next(bb.parameters()).device}, "
            f"v_head device: {next(uu.v_head.parameters()).device if hasattr(uu,'v_head') and uu.v_head is not None else None}"
            )
                
                
        # CRITICAL: Restore dataset if parent filtered it (double-check after init)
        if train_dataset is not None:
            # Check if dataset was filtered by parent
            if hasattr(self, 'dataset') and len(self.dataset) == 0 and original_len > 0:
                logger.warning(f"⚠️ Parent class filtered dataset from {original_len} to 0 rows. Restoring...")
                self.dataset = train_dataset
                if hasattr(self, 'train_dataset'):
                    self.train_dataset = train_dataset
                # Also need to recreate dataloader if it was created with empty dataset
                if hasattr(self, 'dataloader'):
                    logger.info("🔄 Recreating dataloader with restored dataset")
                    try:
                        self.dataloader = self.prepare_dataloader(self.dataset, self.data_collator)
                    except Exception as e:
                        logger.warning(f"⚠️ Failed to recreate dataloader: {e}")
            
            # Also ensure train_dataset is set if parent didn't set it
            if not hasattr(self, 'train_dataset') or self.train_dataset is None:
                self.train_dataset = train_dataset
                if hasattr(self, 'dataset'):
                    self.dataset = train_dataset
            
            # Verify dataset has data after parent init
            if hasattr(self, 'dataset') and len(self.dataset) == 0:
                logger.error(f"❌ Dataset is empty after parent __init__! Original had {original_len} rows")
                # Force restore
                self.dataset = train_dataset
                if hasattr(self, 'train_dataset'):
                    self.train_dataset = train_dataset
                # Recreate dataloader
                if hasattr(self, 'dataloader'):
                    try:
                        self.dataloader = self.prepare_dataloader(self.dataset, self.data_collator)
                    except Exception as e:
                        logger.warning(f"⚠️ Failed to recreate dataloader: {e}")
            elif hasattr(self, 'dataset'):
                logger.info(f"✅ Dataset preserved: {len(self.dataset)} rows after parent __init__")
    
        # Ensure our custom collator is used (parent might have created a default one)
        if custom_collator is not None:
            self.data_collator = custom_collator
            print(f"✅ Using custom data collator: {type(self.data_collator).__name__}")
        else:
            print(f"⚠️ No custom collator provided, using: {type(self.data_collator).__name__}")
        
        # Now safe to access self.args and other parent attributes
        # Disable warning for right-padding in decoder-only generation
        try:
            # Clear internal pad tensor so generation won't warn
            self.generation_config._pad_token_tensor = None
        except Exception:
            pass
        
        # Use provided ad_facts_list or fallback to global
        if ad_facts_list is None:
            ad_facts_list = GLOBAL_AD_FACTS_LIST
        self.ad_facts_list = ad_facts_list
        
        # Store no-ad responses for detectability
        self.no_ad_responses: List[str] = []
        
        # Initialize dataloader iterator (now safe since super().__init__ completed)
        # Verify self.args exists before accessing it
        if not hasattr(self, 'args'):
            raise RuntimeError("self.args not initialized by parent class")
        self._dataloader_iter = None
        
        # train_dataset might be set by parent class or will be set later in make_trainer
        # So we'll initialize the dataloader lazily when needed
        if hasattr(self, 'train_dataset') and self.train_dataset is not None:
            self._reset_dataloader()
        else:
            print("⚠️ train_dataset not yet available, will initialize dataloader when needed")
        u = self.accelerator.unwrap_model(self.model)
        u = self.accelerator.unwrap_model(self.model)
        logger.info(f"🔥 Final policy device: {next(u.parameters()).device}")
        
    @staticmethod
    def ensure_llamafactory_tuple_output(model, logger):
        import types, torch
        if hasattr(model, "_patched_forward_llf"):
            return model

        original_forward = model.forward

        def patched_forward(self, *args, **kwargs):
            return_dict = kwargs.pop("return_dict", True)
            out = original_forward(*args, return_dict=return_dict, **kwargs)

            # ✅ TRL ValueHead common case: (lm_out, values)
            if isinstance(out, tuple) and len(out) >= 2 and hasattr(out[0], "logits"):
                lm_out = out[0]
                logits = lm_out.logits
                pkv = getattr(lm_out, "past_key_values", None)
                values = out[1]

                # normalize values shape to [bs, seq]
                if isinstance(values, torch.Tensor):
                    if values.dim() == 1:
                        values = values.unsqueeze(1).expand(-1, logits.shape[1])
                    if values.dim() == 2 and values.shape[1] == 1:
                        values = values.expand(-1, logits.shape[1])

                return (logits, pkv, values)

            # HF output object case (has logits)
            if hasattr(out, "logits"):
                logits = out.logits
                pkv = getattr(out, "past_key_values", None)
                values = getattr(out, "value", None)

                if torch.is_tensor(values):
                    # normalize values shape to [bs, seq]
                    if values.dim() == 1:
                        values = values.unsqueeze(1).expand(-1, logits.shape[1])
                    if values.dim() == 2 and values.shape[1] == 1:
                        values = values.expand(-1, logits.shape[1])
                    return (logits, pkv, values)

                # couldn't find value — just return original out (non-fatal)
                return out

            # last resort
            return out

        model.forward = types.MethodType(patched_forward, model)
        model._patched_forward_llf = True
        return model

    def prepare_dataloader(self, dataset, data_collator):
        import torch.utils.data

        # prefer preserved original dataset
        if getattr(self, "_original_train_dataset", None) is not None:
            if len(self._original_train_dataset) > 0:
                dataset = self._original_train_dataset
                self.dataset = dataset
                self.train_dataset = dataset

        if dataset is None or len(dataset) == 0:
            raise ValueError("❌ Cannot create dataloader with empty dataset")

        # ✅ use TrainingArguments batch size (matches your _reset_dataloader)
        bs = getattr(self.args, "per_device_train_batch_size", None)
        if bs is None:
            # last resort fallback
            bs = getattr(getattr(self, "training_args", None), "per_device_train_batch_size", 1)

        return torch.utils.data.DataLoader(
            dataset,
            batch_size=bs,
            collate_fn=data_collator,
            shuffle=True,
            drop_last=False,
            num_workers=getattr(self.args, "dataloader_num_workers", 0),
            pin_memory=getattr(self.args, "dataloader_pin_memory", False),
        )

    def _reset_dataloader(self):
        """Reset dataloader + iterator using ONE source of truth."""
        if getattr(self, "train_dataset", None) is None:
            raise RuntimeError("train_dataset not available. Set it before calling _reset_dataloader().")
        if getattr(self, "data_collator", None) is None:
            raise RuntimeError("data_collator not available.")

        # IMPORTANT: HF datasets + num_workers>0 is often pain. Start with 0.
        if hasattr(self.args, "dataloader_num_workers"):
            self.args.dataloader_num_workers = 0

        self.dataloader = self.prepare_dataloader(self.train_dataset, self.data_collator)
        self._dataloader_iter = iter(self.dataloader)

        bs = getattr(self.args, "per_device_train_batch_size", None)
        print(f"✅ Dataloader reset: {len(self.dataloader)} batches | batch_size={bs} | collator={type(self.data_collator).__name__}")

    def _make_batch(self):
        """Get the next batch from the dataloader, resetting if needed."""
        try:
            if self._dataloader_iter is None:
                self._reset_dataloader()
            batch = next(self._dataloader_iter)
            if batch is None:
                raise RuntimeError("Got None batch from dataloader")
            return batch
        except (StopIteration, UnboundLocalError):
            print("🔄 Dataloader exhausted, resetting iterator...")
            self._reset_dataloader()
            try:
                batch = next(self._dataloader_iter)
                if batch is None:
                    raise RuntimeError("Got None batch from dataloader after reset")
                return batch
            except StopIteration:
                raise RuntimeError("Dataloader is empty - no data available for training")
            except Exception as e:
                print(f"❌ Failed to get batch after reset: {e}")
                raise RuntimeError(f"Failed to get batch: {e}")
    
   

    @torch.no_grad()
    def get_inputs(self, batch):
        """Generate responses with and without ads."""
        # Handle both list-of-dicts and batched-dict formats from DataLoader
        if isinstance(batch, dict) and "vague_query" in batch:
            # Batched dict format - convert to list of dicts
            batch_size = len(batch["vague_query"])
            batch = [
                {key: batch[key][i] if isinstance(batch[key], (list, tuple)) else batch[key]
                 for key in batch.keys()}
                for i in range(batch_size)
            ]
        
        # Decode raw queries for logging
        raw_qs = [ex["vague_query"] for ex in batch]
        self._last_batch_raw_qs = raw_qs

        # Extract ad metadata
        ad_products  = [ex["ad_product"] for ex in batch]
        brands       = [ex["brand"] for ex in batch]
        urls         = [ex["url"] for ex in batch]
        descriptions = [ex["ad_description"] for ex in batch]
        dataset_idxs = [ex["dataset_idx"] for ex in batch]

        # Build prompts
        full_prompts_ad = []
        full_prompts_no_ad = []
        ad_texts = []

        for i, q in enumerate(raw_qs):
            ad_text = (
                f"Product: {ad_products[i]}\n"
                f"Brand:   {brands[i]}\n"
                f"URL:     {urls[i]}\n"
                f"Desc:    {descriptions[i]}"
            )
            full_prompts_ad.append(get_prompt_with_ad(q, ad_text))
            full_prompts_no_ad.append(get_prompt_without_ad(q))
            ad_texts.append(ad_text)

        self._last_batch_ad_texts = ad_texts
        self._last_batch_dataset_idxs = dataset_idxs

        # --- Use collator for tokenization & padding ---
        # Tokenize prompts explicitly for clarity and error handling
        batch_with_ad = self.data_collator([
            {"text": prompt, "dataset_idx": idx}
            for prompt, idx in zip(full_prompts_ad, dataset_idxs)
        ])
        batch_no_ad = self.data_collator([
            {"text": prompt, "dataset_idx": idx}
            for prompt, idx in zip(full_prompts_no_ad, dataset_idxs)
        ])

      
        model = self.model  # possibly wrapped
        u = self.accelerator.unwrap_model(model)
        base = getattr(u, "pretrained_model", u)
        model_device = next(base.parameters()).device

        if model_device.type != "cuda":
            raise RuntimeError(
                f"Generation is on {model_device} — should be cuda. "
                "Accelerate did not place model on GPU."
            )

        
    
        # Debug: log device info (only first time)
        if not hasattr(self, '_device_logged'):
            cur = getattr(self, "current_device", None) or getattr(self.accelerator, "device", None)
            logger.info(f"🔧 Model device: {model_device}, Current device: {cur}")
            if model_device.type == "cpu" and torch.cuda.is_available():
                logger.warning(f"⚠️ Model is on CPU but GPU is available - this will be very slow!")
            self._device_logged = True
        
        # Move inputs to model's device (not self.current_device which might be wrong)
        input_ids_ad = batch_with_ad["input_ids"].to(model_device)
        attention_mask_ad = batch_with_ad["attention_mask"].to(model_device)
        input_ids_no_ad = batch_no_ad["input_ids"].to(model_device)
        attention_mask_no_ad = batch_no_ad["attention_mask"].to(model_device)

        # --- Generate responses ---
        # gen_kwargs = self.generation_config.to_dict()
        # for k in ["skip_special_tokens", "max_length", "pad_token_id", "eos_token_id"]:
        #     gen_kwargs.pop(k, None)

        # Generate with ads
        pad_id = self._custom_tokenizer.pad_token_id

        gen_out_ad = model.generate(
            generation_config=self.generation_config,
            input_ids=input_ids_ad,
            attention_mask=attention_mask_ad,
            pad_token_id=pad_id,
        )

        gen_out_no_ad = model.generate(
            generation_config=self.generation_config,
            input_ids=input_ids_no_ad,
            attention_mask=attention_mask_no_ad,
            pad_token_id=pad_id,
        )

        # --- Extract responses relative to prompt length ---
        response_tensors_ad = []
        response_tensors_no_ad = []
        full_prompt_len_ad = input_ids_ad.size(1)
        full_prompt_len_no = input_ids_no_ad.size(1)
        for i in range(input_ids_ad.size(0)):
            response_tensors_ad.append(gen_out_ad[i, full_prompt_len_ad:])
            response_tensors_no_ad.append(gen_out_no_ad[i, full_prompt_len_no:])

        # Store no-ad responses for detectability
        decoded_no_ad = [
            self._custom_tokenizer.decode(t.detach().cpu().tolist(), skip_special_tokens=True)
            for t in response_tensors_no_ad
        ]
        self.no_ad_responses.extend(decoded_no_ad)
        self._last_batch_no_ads = decoded_no_ad

        for t in decoded_no_ad:
            PPO_NO_AD_BUFFER.append(t)

        # Return query tensors (with-ad prompts) and response tensors
        # Ensure they are lists of tensors (not batched tensors)
        query_tensors = []
        for i in range(input_ids_ad.size(0)):
            nonpad = attention_mask_ad[i].nonzero(as_tuple=False)
            if nonpad.numel() == 0:
                query_tensors.append(input_ids_ad[i, -1:].clone())
            else:
                first = nonpad[0].item()
                query_tensors.append(input_ids_ad[i, first:].clone())

        response_tensors = [r.clone() for r in response_tensors_ad]
        return query_tensors, response_tensors

    def prepare_model_inputs(self, queries, responses):
        """
        Build model_inputs from query/response token tensors without any text decode/re-tokenize.

        Args:
            queries: List[torch.Tensor], each shape [q_len]
            responses: List[torch.Tensor], each shape [r_len]
        Returns:
            Dict[str, torch.Tensor]: {"input_ids": [B, T], "attention_mask": [B, T]}
            Both tensors are placed on the policy model's device.
        """
        import torch

        # ✅ policy device (works with accelerate wrappers)
        u = self.accelerator.unwrap_model(self.model)
        base = getattr(u, "pretrained_model", u)
        policy_device = next(base.parameters()).device
        
        # Defensive: allow single tensors too
        if isinstance(queries, torch.Tensor):
            queries = [queries]
        if isinstance(responses, torch.Tensor):
            responses = [responses]

        if len(queries) != len(responses):
            raise ValueError(f"queries/responses length mismatch: {len(queries)} vs {len(responses)}")

        # pad_token_id fallback chain
        tok = getattr(self, "_custom_tokenizer", None) or getattr(self, "tokenizer", None)
        if tok is not None and tok.pad_token_id is not None:
            pad_token_id = tok.pad_token_id
        elif tok is not None and tok.eos_token_id is not None:
            pad_token_id = tok.eos_token_id
        else:
            pad_token_id = 0

        input_ids_list = []
        attn_list = []

        for q, r in zip(queries, responses):
            if not isinstance(q, torch.Tensor) or not isinstance(r, torch.Tensor):
                raise TypeError("prepare_model_inputs expects token tensors (queries/responses).")

            q = q.to(policy_device)
            r = r.to(policy_device)

            full = torch.cat([q, r], dim=0)  # [T]
            input_ids_list.append(full)

            attn = torch.ones_like(full, dtype=torch.long, device=policy_device)  # [T]
            attn_list.append(attn)

        max_len = max(t.size(0) for t in input_ids_list)
        batch_size = len(input_ids_list)

        input_ids = torch.full(
            (batch_size, max_len),
            pad_token_id,
            dtype=torch.long,
            device=policy_device,
        )
        attention_mask = torch.zeros(
            (batch_size, max_len),
            dtype=torch.long,
            device=policy_device,
        )

        for i, (seq, attn) in enumerate(zip(input_ids_list, attn_list)):
            seq_len = seq.size(0)
            input_ids[i, :seq_len] = seq
            attention_mask[i, :seq_len] = attn

        return {"input_ids": input_ids, "attention_mask": attention_mask}

    @torch.no_grad()
    def get_rewards(self, queries, responses):
        #  response text only
        responses_text = [
            self._custom_tokenizer.decode(r_ids.detach().cpu().tolist(), skip_special_tokens=True)
            for r_ids in responses
        ]

        # udge wants raw user query (NOT decoded training prompt)
        raw_qs = getattr(self, "_last_batch_raw_qs", [""] * len(responses_text))

        # ad_info as dict aligned to dataset_idx
        dataset_idxs = getattr(self, "_last_batch_dataset_idxs", list(range(len(responses_text))))
        ad_infos = []
        for idx in dataset_idxs:
            if 0 <= idx < len(self.ad_facts_list):
                ad_infos.append(self.ad_facts_list[idx])
            else:
                logger.warning(f"Dataset idx out of range: {idx}")
                ad_infos.append({"brand":"", "ad_product":"", "url":"", "ad_description":""})

        # detectability: pop paired no-ad completions (from  global deque buffer)
        # Paired no-ad completions from *this* batch (preferred)
        no_ads = getattr(self, "_last_batch_no_ads", [""] * len(responses_text))

        # Fallback if missing / wrong length
        if len(no_ads) != len(responses_text):
            logger.warning("detectability: no_ads length mismatch; falling back to empty strings.")
            no_ads = [""] * len(responses_text)

        if any(x == "" for x in no_ads):
            logger.warning("detectability: missing no-ad responses for some items.")
        async def batch_judge():
            sc_tasks  = [judge_coherence_async(q, r) for q, r in zip(raw_qs, responses_text)]
            sh_tasks  = [judge_helpfulness_async(q, r) for q, r in zip(raw_qs, responses_text)]
            ss_tasks  = [judge_ad_salience_async(q, r, a) for q, r, a in zip(raw_qs, responses_text, ad_infos)]
            det_tasks = [judge_detectability_async(r, na) for r, na in zip(responses_text, no_ads)]
            
            return await asyncio.gather(
                asyncio.gather(*sc_tasks),
                asyncio.gather(*sh_tasks),
                asyncio.gather(*ss_tasks),
                asyncio.gather(*det_tasks),
            )

        sc_list, sh_list, ss_list, det_list = asyncio.run(batch_judge())

        scores = []

        for i, (user_query, response, sc, sh, ss, det, ad_info) in enumerate(
            zip(raw_qs, responses_text, sc_list, sh_list, ss_list, det_list, ad_infos)
        ):
            # dataset idx for logging (optional)
            dataset_idx = dataset_idxs[i] if i < len(dataset_idxs) else None

            logger.info(f"➡️ Item {i} User Query: {user_query}")
            logger.info(f"➡️ Item {i} Ad info: {ad_info}")  # dict
            logger.info(f"➡️ Item {i} Generated with-ad response: {response}")
            logger.info(f"➡️ Item {i} Generated no-ad response: {no_ads[i]}")

            logger.info(
                f"🧐 Judge details for item {i}: "
                f"Coherence={sc.get('Coherence Score', 0)}, "
                f"Helpfulness={sh.get('H1', 0)}, "
                f"Ad Salience={ss.get('Ad Salience Score', 0)}, "
                f"Detectability={det.get('detectability_cosine', 0)}"
            )

            det_cos = det.get("detectability_cosine", 0) or 0
            det_cos = max(min(float(det_cos), 1.0), -1.0)

            coherence_score   = float(sc.get("Coherence Score", 0) or 0)
            helpfulness_score = float(sh.get("H1", 0) or 0)
            salience_score    = float(ss.get("Ad Salience Score", 0) or 0)

            total = coherence_score + helpfulness_score + salience_score - det_cos

            reward_device = responses[0].device if len(responses) else next(self.model.parameters()).device
            scores.append(torch.tensor(total, device=reward_device))
            TRAINING_LOGS.append({
                "query_idx": dataset_idx,
                "user_query": user_query,
                "ad_id": ad_info.get("ad_id"),
                "ad_product": ad_info.get("ad_product"),
                "brand": ad_info.get("brand"),
                "url": ad_info.get("url"),
                "ad_description": ad_info.get("ad_description"),
                "response_with_ad": response,
                "response_without_ad": no_ads[i],
                "C1": sc.get("C1", 0),
                "C2": sc.get("C2", 0),
                "C3": sc.get("C3", 0),
                "C4": sc.get("C4", 0),
                "coherence_score": sc.get("Coherence Score", 0),
                "coherence_explanation": sc.get("Coherence Explanation", ""),
                "H1": sh.get("H1", 0),
                "helpfulness_explanation": sh.get("Helpfulness Explanation", ""),
                "S1": ss.get("S1", 0),
                "S2": ss.get("S2", 0),
                "S3": ss.get("S3", 0),
                "salience_score": ss.get("Ad Salience Score", 0),
                "salience_explanation": ss.get("Ad Salience Explanation", ""),
                "detectability_cosine": det.get("detectability_cosine", 0),
                "similarity_cosine": det.get("similarity_cosine", 0),
                "total_reward": total,
            })

        return scores

    def compute_rewards(
        self,
        scores: torch.FloatTensor,
        logprobs: torch.FloatTensor,
        ref_logprobs: torch.FloatTensor,
        masks: torch.LongTensor,
    ):
        """
        Override compute_rewards to ensure device consistency and allow penalty customization.
        
        Args:
            scores: Reward scores from judges, shape (batch_size)
            logprobs: Log probabilities from policy model, shape (batch_size, response_length)
            ref_logprobs: Log probabilities from reference model, shape (batch_size, response_length)
            masks: Attention masks, shape (batch_size, response_length)
        
        Returns:
            rewards: Per-token rewards, shape (batch_size, response_length)
            non_score_reward: KL penalty per token, shape (batch_size, response_length)
            kls: KL divergence per token, shape (batch_size, response_length)
        """
        import torch
        
        # CRITICAL: Ensure all tensors are on the same device
        # Get device from logprobs (policy model output, should be on CUDA)
        target_device = logprobs.device
        
        # Move ref_logprobs to same device as logprobs if needed
        if ref_logprobs.device != target_device:
            ref_logprobs = ref_logprobs.to(target_device)
        
        # Move scores and masks to same device if needed
        if scores.device != target_device:
            scores = scores.to(target_device)
        if masks.device != target_device:
            masks = masks.to(target_device)
        
        # Call parent's compute_rewards with device-consistent tensors
        # This will compute: rewards = scores - kl_penalty_coef * kl_penalty
        rewards, non_score_reward, kls = super().compute_rewards(
            scores=scores,
            logprobs=logprobs,
            ref_logprobs=ref_logprobs,
            masks=masks,
        )
        
        # Log KL penalty statistics for monitoring
        # non_score_reward is the KL penalty per token (negative because it's subtracted)
        # kls is the raw KL divergence per token
        if kls.numel() > 0:
            # Get KL penalty coefficient from config (default 0.1)
            kl_coef = getattr(self.config, 'kl_penalty_coef', 0.1) if hasattr(self, 'config') else 0.1
            
            # Compute statistics (only for non-masked tokens)
            masked_kls = kls[masks.bool()]
            if masked_kls.numel() > 0:
                mean_kl = masked_kls.mean().item()
                max_kl = masked_kls.max().item()
                mean_kl_penalty = (-non_score_reward[masks.bool()]).mean().item()  # non_score_reward is negative
                
                # Log every few steps to avoid spam
                if not hasattr(self, '_kl_log_counter'):
                    self._kl_log_counter = 0
                self._kl_log_counter += 1
                
                if self._kl_log_counter % 10 == 1:  # Log every 10th call
                    logger.info(
                        f"📊 KL Penalty Stats: mean_kl={mean_kl:.4f}, max_kl={max_kl:.4f}, "
                        f"mean_penalty={mean_kl_penalty:.4f}, kl_coef={kl_coef:.3f}"
                    )
        
        return rewards, non_score_reward, kls

    def batched_forward_pass(
        self,
        model,
        queries,
        responses,
        model_inputs,
        return_logits: bool = False,
        response_masks=None,
    ):
        def _unwrap(m):
            return self.accelerator.unwrap_model(m) if m is not None else None

        um = _unwrap(model)
        u_ref = _unwrap(getattr(self, "ref_model", None))

        is_ref = (model is None) or (u_ref is not None and um is u_ref)
        if um is not None and next(getattr(um, "pretrained_model", um).parameters()).device.type == "cpu":
            is_ref = True

        if is_ref:
            m_u = _unwrap(self._ref_model) or self._ref_model
            base = getattr(m_u, "pretrained_model", m_u)
        else:
            m_u = self.accelerator.unwrap_model(self.model)
            base = getattr(m_u, "pretrained_model", m_u)
        # device where this forward will run
        model_device = next(base.parameters()).device

        # LlamaFactory mini-batching
        bs = len(queries)
        fbs = getattr(self.config, "mini_batch_size", bs)

        all_logprobs, all_logits, all_masks, all_values = [], [], [], []

        for i in range(math.ceil(bs / fbs)):
            input_kwargs = {k: v[i * fbs : (i + 1) * fbs] for k, v in model_inputs.items()}
            query_batch = queries[i * fbs : (i + 1) * fbs]
            response_batch = responses[i * fbs : (i + 1) * fbs]

            # move inputs to model_device (CUDA for policy; CPU for ref if you keep ref on CPU)
            for k, v in list(input_kwargs.items()):
                if torch.is_tensor(v) and v.device != model_device:
                    input_kwargs[k] = v.to(model_device)
            if "attention_mask" in input_kwargs:
                input_kwargs["attention_mask"] = input_kwargs["attention_mask"].long()

            input_ids = input_kwargs["input_ids"]
            attention_mask = input_kwargs.get("attention_mask", None)
            if attention_mask is None:
                attention_mask = torch.ones_like(input_ids, dtype=torch.long, device=model_device)
                input_kwargs["attention_mask"] = attention_mask
            elif attention_mask.dtype != torch.long:
                attention_mask = attention_mask.long()
                input_kwargs["attention_mask"] = attention_mask

            # if this model has v_head, we need hidden states to compute values
            need_values = hasattr(m_u, "v_head") and m_u.v_head is not None

            with self.amp_context:
                out = base(
                    **input_kwargs,
                    return_dict=True,
                    use_cache=False,
                    output_hidden_states=need_values,
                )

            logits = out.logits  # [B,T,V]

            # values:
            if need_values:
                hs = out.hidden_states[-1]     # [B,T,H]
                values = m_u.v_head(hs).squeeze(-1)  # [B,T]
            else:
                # reference model: values not used; return zeros with correct shape
                values = torch.zeros(
                    logits.shape[0], logits.shape[1],
                    device=logits.device,
                    dtype=logits.dtype,
                )

            # normalize values to [B,T]
            if values.dim() == 1:
                values = values.unsqueeze(1).expand(-1, logits.shape[1])
            elif values.dim() == 2 and values.shape[1] == 1:
                values = values.expand(-1, logits.shape[1])
            elif values.dim() == 3 and values.shape[-1] == 1:
                values = values.squeeze(-1)

            # logprobs for shifted labels
            logits_s = logits[:, :-1, :]
            labels = input_ids[:, 1:]
            logp = torch.log_softmax(logits_s, dim=-1)
            logprobs = logp.gather(-1, labels.unsqueeze(-1)).squeeze(-1)  # [B,T-1]

            # masks (shifted)
            masks = torch.zeros_like(attention_mask)
            masks[:, :-1] = attention_mask[:, 1:]

            # mask to response region
            for j in range(len(query_batch)):
                start = max(0, len(query_batch[j]) - 1)
                end = min(start + len(response_batch[j]), masks.shape[1])
                masks[j, :start] = 0
                masks[j, end:] = 0

                if response_masks is not None:
                    rm = response_masks[i * fbs : (i + 1) * fbs][j]
                    rm = rm.to(model_device) if torch.is_tensor(rm) else torch.tensor(rm, device=model_device)
                    rm = rm.long().view(-1)
                    resp_len = end - start
                    if rm.numel() != resp_len:
                        rm = rm[:resp_len] if rm.numel() > resp_len else torch.cat(
                            [rm, torch.ones(resp_len - rm.numel(), device=model_device, dtype=rm.dtype)]
                        )
                    masks[j, start:end] = masks[j, start:end] * rm

            all_logprobs.append(logprobs)
            all_values.append(values)
            all_masks.append(masks)
            if return_logits:
                all_logits.append(logits)

        return (
            torch.cat(all_logprobs, dim=0),
            torch.cat(all_logits, dim=0)[:, :-1] if return_logits else None,
            torch.cat(all_values, dim=0)[:, :-1],
            torch.cat(all_masks, dim=0)[:, :-1],
        )

    def ppo_train(self, resume_from_checkpoint=None, start_step=0, start_query_idx=0):
        u = self.accelerator.unwrap_model(self.model)
        base = getattr(u, "pretrained_model", u)
        if (not hasattr(u, "v_head")) or (u.v_head is None) or (next(base.parameters()).device.type != "cuda"):

            print("🧯 Restoring ValueHead policy onto CUDA (self.model was overwritten)...")

            if not hasattr(self, "_policy_with_vhead") or self._policy_with_vhead is None:
                raise RuntimeError("Missing self._policy_with_vhead to restore from.")

            # restore correct model object
            self.model = self._policy_with_vhead

            # move to accelerator device (cuda)
            dev = str(self.accelerator.device)  # e.g. 'cuda'
            self.model = force_valuehead_all_cuda(self.model, dev)

            # IMPORTANT: re-create optimizer over restored parameters if needed
            if not hasattr(self, "optimizer") or self.optimizer is None:
                lr = getattr(self.args, "learning_rate", 5e-5)
                wd = getattr(self.args, "weight_decay", 0.0)
                self.optimizer = torch.optim.AdamW(self.model.parameters(), lr=lr, weight_decay=wd)

            # prepare together so accelerate wraps consistently
            self.model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)

            u2 = self.accelerator.unwrap_model(self.model)
            print("✅ Restored model type:", type(u2), "has v_head:", hasattr(u2, "v_head"),
                "device:", next(u2.parameters()).device)
        # Clear GPU cache at start to free up memory
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
            torch.cuda.synchronize()
            total_mem = torch.cuda.get_device_properties(0).total_memory
            allocated_mem = torch.cuda.memory_allocated(0)
            free_mem = (total_mem - allocated_mem) / 1e9  # Convert bytes to GB
            print(f"🧹 Cleared GPU cache. Free memory: {free_mem:.2f} GB")
        
        print("✅ USING CUSTOM ppo_train!")
        print(f"📊 Resume info: checkpoint={resume_from_checkpoint}, step={start_step}, query_idx={start_query_idx}")

        total_loss = 0.0
        total_reward = 0.0
        total_steps = 0
        
        # Calculate total steps for progress tracking
        total_epochs = self.finetuning_args.ppo_epochs
        batches_per_epoch = len(self.dataloader)
        total_batches = total_epochs * batches_per_epoch
        
        print(f"📈 Training plan: {total_epochs} epochs × {batches_per_epoch} batches = {total_batches} total batches")
        print(f"⏰ Started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

        # Reset dataloader at the start of training
        self._reset_dataloader()
        
        # Time tracking
        training_start_time = time.time()
        step_times = []
        
        # Track current step for checkpoint saving
        self._current_step = start_step
        self.total_steps = 0  # Track total completed steps

        # If resuming, calculate which epoch and batch to start from
        start_epoch = 0
        start_batch_idx = 0
        if start_step > 0:
            start_epoch = start_step // batches_per_epoch
            start_batch_idx = start_step % batches_per_epoch
            print(f"⏯ Resuming from step {start_step} (epoch {start_epoch + 1}, batch {start_batch_idx + 1})")
            # Skip batches in the dataloader to get to the right position
            if start_batch_idx > 0:
                # Reset and skip to the right position
                self._reset_dataloader()
                for _ in range(start_batch_idx):
                    try:
                        next(self._dataloader_iter)
                    except StopIteration:
                        self._reset_dataloader()
                        break

        for epoch in range(start_epoch, self.finetuning_args.ppo_epochs):
            print(f"\n{'='*60}")
            print(f"📚 EPOCH {epoch + 1}/{total_epochs}")
            print(f"{'='*60}")
            
            # Determine starting batch index for this epoch
            batch_start = start_batch_idx if epoch == start_epoch else 0
            
            for batch_idx in range(batch_start, batches_per_epoch):
                step = epoch * batches_per_epoch + batch_idx
                step_start_time = time.time()
                
                try:
                    batch = self._make_batch()
                    if not batch:
                        print(f"⚠️ Skipping step {step}: empty batch")
                        continue

                    # Progress indicator
                    progress = (step + 1) / total_batches * 100
                    print(f"\n🔁 Step {step + 1}/{total_batches} ({progress:.1f}%) | Epoch {epoch + 1}/{total_epochs} | Batch {batch_idx + 1}/{batches_per_epoch}")
                    print(f"⏱️  Time: {datetime.now().strftime('%H:%M:%S')}")
                    
                    self.model.eval()
                    
                    print("  📝 Generating responses...")
                    gen_start = time.time()
                    queries, responses = self.get_inputs(batch)
                    gen_time = time.time() - gen_start
                    print(f"  ✅ Generation complete ({gen_time:.1f}s)")
                    
                    print("  🧐 Calling judges...")
                    judge_start = time.time()
                    rewards = self.get_rewards(queries, responses)
                    judge_time = time.time() - judge_start
                    print(f"  ✅ Judging complete ({judge_time:.1f}s)")

                    if not rewards:
                        print(f"  ⚠️ No rewards returned, skipping optimization")
                        continue

                    print("  🔄 Updating model...")
                    self.model.train()
                    update_start = time.time()
                    stats = self.step(queries, responses, rewards)
                    update_time = time.time() - update_start

                    step_loss = float(stats.get("ppo/loss/total", 0.0))
                    step_reward = torch.stack(rewards).mean().item()

                    total_loss += step_loss
                    total_reward += step_reward
                    total_steps += 1
                    self.total_steps = total_steps  # Update for interruption handling
                    self._current_step = step + 1  # Update current step
                    
                    step_time = time.time() - step_start_time
                    step_times.append(step_time)
                    
                    # Calculate ETA
                    avg_step_time = sum(step_times[-10:]) / min(10, len(step_times))  # Average of last 10 steps
                    remaining_steps = total_batches - (step + 1)
                    eta_seconds = avg_step_time * remaining_steps
                    eta = timedelta(seconds=int(eta_seconds))

                    print(f"  ✅ Step complete — Loss: {step_loss:.4f}, Reward: {step_reward:.4f}")
                    print(f"  ⏱️  Step time: {step_time:.1f}s (Gen: {gen_time:.1f}s, Judge: {judge_time:.1f}s, Update: {update_time:.1f}s)")
                    print(f"  📊 Avg step time: {avg_step_time:.1f}s | ETA: {eta}")
                    print(f"  📈 Progress: {len(TRAINING_LOGS)} total judge entries")
                    
                    # Save logs incrementally every 50 steps to avoid losing progress
                    if (step + 1) % 50 == 0:
                        try:
                            log_path = Path(self.training_args.output_dir) / "ppo_judging_log.csv"
                            pd.DataFrame(TRAINING_LOGS).to_csv(log_path, index=False)
                            elapsed = time.time() - training_start_time
                            elapsed_str = str(timedelta(seconds=int(elapsed)))
                            print(f"  💾 Saved incremental logs: {len(TRAINING_LOGS)} entries | Elapsed: {elapsed_str}")
                        except Exception as e:
                            logger.warning(f"⚠️ Failed to save incremental logs: {e}")
                    
                    # Save model checkpoint every 100 steps (configurable via save_steps)
                    save_steps = getattr(self.training_args, 'save_steps', 100)
                    if (step + 1) % save_steps == 0:
                        try:
                            print(f"  💾 Saving checkpoint at step {step + 1}...")
                            # Save using trainer's save_model which creates checkpoint-* directories
                            checkpoint_dir = Path(self.training_args.output_dir) / f"checkpoint-{step + 1}"
                            checkpoint_dir.mkdir(parents=True, exist_ok=True)
                            
                            # Save model and tokenizer
                            self.model.save_pretrained(checkpoint_dir)
                            if hasattr(self, '_custom_tokenizer') and self._custom_tokenizer:
                                self._custom_tokenizer.save_pretrained(checkpoint_dir)
                            
                            # Save optimizer state if available
                            if hasattr(self, 'optimizer') and self.optimizer:
                                torch.save(self.optimizer.state_dict(), checkpoint_dir / "optimizer.pt")
                            
                            # Save training position
                            last_pos = {"query_index": step + 1}
                            with open(Path(self.training_args.output_dir) / "last_query_position.json", "w") as f:
                                json.dump(last_pos, f)
                            
                            print(f"  ✅ Checkpoint saved to {checkpoint_dir}")
                        except Exception as e:
                            logger.warning(f"⚠️ Failed to save checkpoint: {e}")
                            import traceback
                            traceback.print_exc()

                except Exception as e:
                    print(f"  ❌ Step {step} failed due to: {e}")
                    import traceback
                    traceback.print_exc()
                    print("❌ Exiting due to error in PPO training")
                    sys.exit(1)

        if total_steps > 0:
            avg_loss = total_loss / total_steps
            avg_reward = total_reward / total_steps
            total_time = time.time() - training_start_time
            total_time_str = str(timedelta(seconds=int(total_time)))
            print(f"\n{'='*60}")
            print(f"🏁 PPO Training Complete!")
            print(f"{'='*60}")
            print(f"📊 Total steps: {total_steps}")
            print(f"📈 Avg Loss: {avg_loss:.4f}")
            print(f"🎯 Avg Reward: {avg_reward:.4f}")
            print(f"⏱️  Total time: {total_time_str}")
            print(f"💾 Total judge entries: {len(TRAINING_LOGS)}")
            print(f"{'='*60}\n")
        else:
            print("❌ PPO training ended with 0 valid steps.")
            sys.exit(1)


def force_valuehead_all_cuda(m, device="cuda:0"):
    import torch

    # normalize "cuda" -> "cuda:0"
    if device == "cuda":
        device = f"cuda:{torch.cuda.current_device()}"

    dev = torch.device(device)

    # IMPORTANT: don't re-move if already on CUDA (prevents tiny alloc OOMs)
    try:
        u = m.pretrained_model if hasattr(m, "pretrained_model") else m
        pdev = next(u.parameters()).device
        if pdev.type == "cuda":
            # still ensure v_head is on cuda
            if hasattr(m, "v_head") and m.v_head is not None:
                m.v_head = m.v_head.to(dev)
            return m
    except StopIteration:
        pass

    m = m.to(dev)

    if hasattr(m, "pretrained_model") and m.pretrained_model is not None:
        m.pretrained_model = m.pretrained_model.to(dev)

    if hasattr(m, "v_head") and m.v_head is not None:
        m.v_head = m.v_head.to(dev)

    # check ONLY .type (not full device equality)
    bad = [(n, p.device) for n, p in m.named_parameters() if p.device.type != dev.type]
    if bad:
        raise RuntimeError(f"Not all params on {dev.type}. Example: {bad[:10]}")
    return m

def make_trainer(
    model_name: str,
    hf_token: str,
    data_path: str,
    ad_facts_list: List[dict],
):
    global GLOBAL_AD_FACTS_LIST
    GLOBAL_AD_FACTS_LIST = ad_facts_list
    saved_policy_with_vhead = None

    # --- Load the tokenizer ---
    tokenizer = AutoTokenizer.from_pretrained(
        model_name, use_fast=True, trust_remote_code=True, token=hf_token
    )

    # ✅ Configure tokenizer once
    tokenizer.padding_side = "left"
    tokenizer.truncation_side = "right"
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token or tokenizer.unk_token
    tokenizer.pad_token_id = tokenizer.convert_tokens_to_ids(tokenizer.pad_token)

    # --- Load the policy (with value head) ---
    device_str = "GPU" if torch.cuda.is_available() else "CPU"
    logger.info(f"💻 Loading model for {device_str} training...")
    try:
        if torch.cuda.is_available():
            try:
                logger.info("📥 Loading policy (CPU load, then move to CUDA)...")
                policy = AutoModelForCausalLMWithValueHead.from_pretrained(
                    model_name,
                    trust_remote_code=True,
                    token=hf_token,  # Use 'token' instead of deprecated 'use_auth_token'
                    torch_dtype=torch.float16,  # Use float16 on GPU
                    attn_implementation="sdpa",

                    low_cpu_mem_usage=True,  # Reduce memory usage during loading
                )
                saved_policy_with_vhead = policy
            except (RuntimeError, ValueError) as e:
                raise
            policy = MyPPOTrainer.ensure_llamafactory_tuple_output(policy, logger)
            logger.info(f"💻 Policy param device after load: {next(policy.parameters()).device}")
        else:
            # Use float32 on CPU
            policy = AutoModelForCausalLMWithValueHead.from_pretrained(
                model_name,
                trust_remote_code=True,
                token=hf_token,  # Use 'token' instead of deprecated 'use_auth_token'
                torch_dtype=torch.float32,  # CPU mode
                device_map=None,
            ).to(DEVICE)
            policy = MyPPOTrainer.ensure_llamafactory_tuple_output(policy, logger)
            logger.info(f"💻 Policy param device after load: {next(policy.parameters()).device}")
    except Exception as e:
        logger.error(f"❌ Failed to load model: {e}")
        raise e

    # Create ref AFTER policy exists, but KEEP ref on CPU
    ref = create_reference_model(policy)
    MyPPOTrainer.ensure_llamafactory_tuple_output(ref, logger)
    if hasattr(ref, "pretrained_model"):
        MyPPOTrainer.ensure_llamafactory_tuple_output(ref.pretrained_model, logger)
    ref.eval()
    for p in ref.parameters():
        p.requires_grad = False
    ref.to("cpu")

    ref.eval()
    for p in ref.parameters():
        p.requires_grad = False

    # --- Load dataset (keep in raw format, tokenization happens in collator) ---
    ds = load_dataset("csv", data_files={"train": data_path})["train"]
    ds = ds.add_column("dataset_idx", list(range(len(ds))))
    
    ds.set_format(type="python")  # Use python format, not torch or arrow

    # --- Collator (single source of truth) ---
    collator = PPODataCollator(tokenizer)

    # --- Trainer args ---
    model_args      = ModelArguments(model_name_or_path=model_name, hf_hub_token=hf_token)
    data_args       = DataArguments(
        template="default",
        dataset=Path(data_path).name,
        dataset_dir=str(Path(data_path).parent),
    )
    # Speed optimization: Allow configurable batch size and epochs via environment variables
    # Reduced GPU batch size from 8 to 4 to avoid OOM errors
    batch_size = int(os.getenv("PPO_BATCH_SIZE", "4" if torch.cuda.is_available() else "4"))
    ppo_epochs = int(os.getenv("PPO_EPOCHS", "2" if torch.cuda.is_available() else "1"))  # Reduced from 4
    max_new_tokens = int(os.getenv("MAX_NEW_TOKENS", "256" if torch.cuda.is_available() else "128"))  # Reduced from 512
    
    print(f"⚙️ Training config: batch_size={batch_size}, epochs={ppo_epochs}, max_new_tokens={max_new_tokens}")
    
    training_args   = TrainingArguments(
        output_dir="logs/ppo_run",
        per_device_train_batch_size=batch_size,
        save_strategy="steps",
        save_steps=100,  # Save less frequently to reduce I/O
        logging_steps=10,  # Log less frequently
        max_grad_norm=1.0,
        gradient_checkpointing=True,
        dataloader_num_workers=0,
        no_cuda=not torch.cuda.is_available(),  # Auto-detect
        dataloader_pin_memory=torch.cuda.is_available(),  # Pin memory on GPU
    )
    finetuning_args = FinetuningArguments(
        ppo_epochs=ppo_epochs, 
        ppo_buffer_size=1,
        reward_model_type="api",  # Using custom get_rewards with API judges, not model-based
        ppo_target=0.1,  # Default KL divergence target for PPO
        ppo_score_norm=False,  # Disable score normalization (can enable if needed)
        ppo_whiten_rewards=False,  # Disable reward whitening (can enable if needed)
    )
    generating_args = GeneratingArguments(
        do_sample=False,
        temperature=None,
        top_k=None,
        top_p=None,
        max_new_tokens=max_new_tokens,
    )


    # --- Build trainer ---
    trainer = MyPPOTrainer(
        model_args      = model_args,
        training_args   = training_args,
        finetuning_args = finetuning_args,
        generating_args = generating_args,
        callbacks       = None,
        model           = policy,
        reward_model    = None,
        ref_model       = None,
        tokenizer       = tokenizer,
        processor       = None,
        data_collator   = collator,
        train_dataset   = ds,
        ad_facts_list   = ad_facts_list,
    )
    trainer.ref_model = ref
    trainer._ref_model = ref
    trainer.ref_model.to("cpu")
    for p in trainer.ref_model.parameters():
        p.requires_grad = False
    trainer.ref_model.eval()
    if saved_policy_with_vhead is not None:
        trainer._policy_with_vhead = saved_policy_with_vhead
    else:
        trainer._policy_with_vhead = trainer.model  # fallback
    

    dev = trainer.accelerator.device
    print("accelerator.device:", trainer.accelerator.device)
    if trainer.ref_model is not None:
        trainer.ref_model.to("cpu")
    
    if trainer.ref_model is not None:
        ru = trainer.accelerator.unwrap_model(trainer.ref_model)
        print("ref device:", next(ru.parameters()).device)  # should be cpu
    pol_u = trainer.accelerator.unwrap_model(trainer.model)
    print("wrapper:", next(pol_u.parameters()).device)
    print("base:", next(pol_u.pretrained_model.parameters()).device)
    print("v_head:", next(pol_u.v_head.parameters()).device)

    if trainer.ref_model is not None:
        ref_u = trainer.accelerator.unwrap_model(trainer.ref_model)
        MyPPOTrainer.ensure_llamafactory_tuple_output(ref_u, logger)
        if hasattr(ref_u, "pretrained_model"):
            MyPPOTrainer.ensure_llamafactory_tuple_output(ref_u.pretrained_model, logger)

  
    print("policy device:", next(trainer.model.parameters()).device)
    if trainer.ref_model is not None:
        print("ref device:", next(trainer.ref_model.parameters()).device)
    # Expose args + objects
    trainer.data_args = data_args
    trainer.model_args = model_args
    trainer.training_args = training_args
    trainer.finetuning_args = finetuning_args
    trainer.generating_args = generating_args
    trainer.train_dataset = ds
    trainer._custom_tokenizer = tokenizer  # still available, but collator is preferred

    # Now that train_dataset is set, initialize the dataloader if it wasn't done in __init__
    if trainer._dataloader_iter is None:
        trainer._reset_dataloader()

    return trainer

